import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Language = 'tr' | 'en';

type LanguageContextValue = {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  tr: {
    'nav.main': 'Ana Menü',
    'nav.settings': 'Ayarlar',
    'nav.companySettings': 'Firma Ayarları',
    'nav.otherSettings': 'Diğer Ayarlar',
    'nav.superAdminSettings': 'Super Admin Ayarlar',
    'nav.logout': 'Çıkış Yap',
    'menu.dashboard': 'Kontrol Paneli',
    'menu.admin': 'Genel Takip Sistemi',
    'menu.personResults': 'Detaylı Kişi Sonuçları',
    'menu.personScores': 'Kişi Skorları Sayfası',
    'menu.gameSend': 'Oyun Gönder',
    'menu.usageSummary': 'Oyun Kullanım Özeti',
    'menu.companySetup': 'Firma Tanımlama',
    'menu.companyAdminSetup': 'Firma Admini Tanımlama',
    'menu.gameSetup': 'Oyun Tanımlama',
    'menu.organization': 'Organizasyon',
    'menu.competencySettings': 'Yetkinlik Ayarları',
    'menu.scriptFiles': 'Komut Dosyaları',
    'breadcrumbs.evaluations': 'Değerlendirmeler',
    'breadcrumbs.personResults': 'Kişi Sonuçları',
    'breadcrumbs.reportDetails': 'Rapor Detayları',
    'titles.personResults': 'Detaylı Kişi Sonuçları',
    'titles.personReport': 'Kapsamlı Değerlendirme Raporu',
    'titles.personResultsSection': 'Kişi Sonuçları',
    'titles.personScores': 'Kişi Skorları Sayfası',
    'tabs.executiveSummary': 'Yönetici Özeti',
    'tabs.competencyDetails': 'Yetkinlik Detayları',
    'tabs.reportAccess': 'Rapor Erişimi',
    'tabs.aiAssistant': 'AI Asistan',
    'tabs.trend': 'Trend Analizi',
    'tabs.summary': 'Özet',
    'tabs.fullReport': 'Tam Rapor',
    'labels.currentEvaluation': 'Son Değerlendirme',
    'labels.completion': 'Tamamlandı',
    'labels.competencyStatus': 'Mevcut Yetkinlik Durumu',
    'labels.competencyStatusDesc': 'Son değerlendirme ve benchmark sonuçları',
    'labels.reportDetails': 'Rapor Detayları',
    'labels.evaluationDate': 'Değerlendirme Tarihi',
    'labels.trendAnalysis': 'Yetkinlik Trend Analizi',
    'labels.lastThreeResults': 'Son 3 değerlendirme sonucu',
    'labels.selectCompetency': 'Yetkinlik Seç',
    'labels.trendTip': 'Sağ panelde trend görmek için bir yetkinlik seçin',
    'labels.currentTag': 'Güncel',
    'labels.comprehensiveAssessment': 'Q4 2024 Kapsamlı Değerlendirme',
    'labels.developingCompetency': 'Gelişen Yetkinlik',
    'titles.dashboard': 'Kontrol Paneli',
    'labels.gameSendStatus': 'Oyun Gönderim Durumu',
    'labels.competencyDistributions': 'Yetkinlik Skor Dağılımları',
    'labels.competencySelection': 'Yetkinlik Seçimi',
    'labels.competencyScore': 'Yetkinlik Puanı',
    'labels.peopleEvaluated': 'Değerlendirme Gönderilen Kişi Sayısı',
    'labels.totalGamesSent': 'Toplam Gönderilen Oyun Sayısı',
    'labels.competencyGameDistribution': 'Yetkinliğe Göre Oyun Dağılımı',
    'buttons.filter': 'Filtrele',
    'buttons.refresh': 'Yenile',
    'buttons.downloadResults': 'Sonuçları İndir',
    'labels.loadingResults': 'Sonuçlar yükleniyor...',
    'labels.noResults': 'Gösterilecek sonuç bulunamadı.',
    'labels.completionDate': 'Tamamlanma Tarihi',
    'labels.detail': 'Detay',
    'labels.goToPersonResults': 'Kişi sonuçlarına git',
    'labels.nameSurname': 'Ad Soyad',
    'labels.pdfPreview': 'PDF Önizleme',
    'labels.pdfLoading': 'PDF yükleniyor...',
    'labels.notEnoughData': 'Yeterli veri yok',
    'labels.authorizationsLoading': 'Yetkilendirmeler yükleniyor...',
    'labels.organizationsLoading': 'Organizasyonlar yükleniyor...',
    'labels.groupsLoading': 'Gruplar yükleniyor...',
    'labels.groups': 'Gruplar',
    'labels.groupName': 'Grup Adı',
    'labels.status': 'Durum',
    'labels.details': 'Detaylar',
    'labels.competenciesLoading': 'Yetkinlikler yükleniyor...',
    'labels.competenciesEmpty': 'Henüz yetkinlik bulunmuyor',
    'labels.selection': 'Seçim',
    'labels.selectPosition': 'Pozisyon seçin',
    'labels.startDate': 'Başlangıç Tarihi',
    'labels.noData': 'Veri yok',
    'labels.totalCredits': 'Toplam Kredi',
    'labels.credits': 'Kredi',
    'labels.fee': 'Ücret',
    'labels.monthlyFeeSample': '120$ /Aylık',
    'labels.creditUsage': 'Kredi Kullanımları',
    'labels.usageSinceSample': '10/04/2025 12:16 tarihinden bugüne',
    'labels.remainingUsage': 'Kalan Kullanımlarım',
    'labels.usedUsage': 'Harcanan Kullanımlarım',
    'labels.date': 'Tarih',
    'labels.invoiceNo': 'Fatura No',
    'labels.credit': 'Kredi',
    'labels.loading': 'Yükleniyor...',
    'labels.noGameData': 'Henüz oyun verisi bulunmuyor',
    'labels.customerFocusMin': 'Müşteri Odaklılık Min Değer',
    'labels.customerFocusMax': 'Müşteri Odaklılık Max Değer',
    'labels.uncertaintyMin': 'Uyumluluk ve Dayanıklılık Min Değer',
    'labels.uncertaintyMax': 'Uyumluluk ve Dayanıklılık Max Değer',
    'labels.ieMin': 'İnsanları Etkileme Min Değer',
    'labels.ieMax': 'İnsanları Etkileme Max Değer',
    'labels.idikMin': 'Güven Veren İşbirliği ve Sinerji Min Değer',
    'labels.idikMax': 'Güven Veren İşbirliği ve Sinerji Max Değer',
    'labels.competencySettingsSheet': 'Yetkinlik Ayarları',
    'labels.competencySettingsTemplateFile': 'yetkinlik_ayarlari_template.xlsx',
    'labels.deleteCompetencyConfirm': 'Bu yetkinlikleri silmek istediğinizden emin misiniz?',
    'labels.competencyDeleted': 'yetkinlik başarıyla silindi!',
    'labels.groupInfo': 'Grup Bilgileri',
    'labels.groupDetailsTitle': 'Grup Detayları',
    'labels.organizationSearchPlaceholder': 'Organizasyon arayın',
    'labels.personSearchPlaceholder': 'Kişi arayın',
    'labels.planetSearchPlaceholder': 'Gezegen arayın',
    'labels.organizationNotFound': 'Organizasyon bulunamadı',
    'labels.personNotFound': 'Kişi bulunamadı',
    'labels.planetNotFound': 'Gezegen bulunamadı',
    'labels.viewDetails': 'Detayı Gör',
    'labels.bulkDelete': 'Toplu Sil',
    'labels.groupsEmpty': 'Henüz grup bulunmuyor',
    'labels.groupsNotFound': 'Arama kriterlerinize uygun grup bulunamadı',
    'labels.groupDetailsSubtitle': 'Grup bilgilerini güncelleyin ve organizasyonları, kişileri ve gezegenleri düzenleyin',
    'labels.planetVenus': 'Venüs',
    'labels.planetTitan': 'Titan',
    'labels.planets': 'Gezegenler',
    'labels.createdAt': 'Oluşturulma',
    'labels.unknown': 'Bilinmeyen',
    'labels.user': 'Kullanıcı',
    'labels.about': 'Hakkında',
    'labels.createGroupDesc': 'Yeni bir grup oluşturun ve organizasyonları, kişileri ve gezegenleri atayın',
    'labels.noOrganizationSelected': 'Henüz organizasyon seçilmedi',
    'labels.noPersonSelected': 'Henüz kişi seçilmedi',
    'labels.noPlanetSelected': 'Henüz gezegen seçilmedi',
    'labels.company': 'Firma',
    'labels.companyName': 'Firma Adı',
    'labels.companyEmail': 'Firma Maili',
    'labels.gameDetailsLoading': 'Oyun detayları yükleniyor...',
    'labels.invoiceLoading': 'Fatura yükleniyor...',
    'labels.uploadInvoice': 'Fatura Yükle',
    'labels.uploadInvoiceOptional': 'Fatura Yükle (Opsiyonel)',
    'labels.deleteGameConfirm': 'Bu oyunu silmek istediğinizden emin misiniz?',
    'labels.companySelect': 'Firma seçin',
    'labels.companyNotFound': 'Firma bulunamadı',
    'labels.loadingData': 'Veriler yükleniyor...',
    'labels.password': 'Şifre',
    'labels.newPasswordOptional': 'Yeni Şifre (Opsiyonel)',
    'labels.deleteAdminConfirm': 'Bu admini silmek istediğinizden emin misiniz?',
    'labels.actionIrreversible': 'Bu işlem geri alınamaz!',
    'labels.assessmentReport': 'DegerlendirmeRaporu',
    'labels.participation': 'Katılım',
    'labels.sampleParticipation': 'Ocak 2020',
    'labels.previousPeriodChange': 'Önceki döneme göre +0.7',
    'labels.positiveGrowth': '%75 pozitif gelişim',
    'labels.percentileRank': 'Percentile Sırası',
    'labels.companyOverall': 'Şirket genelinde',
    'labels.executiveSummarySample': 'Sarah Johnson, Q4 2024 değerlendirmesinde 8.4/10 genel skorla üstün performans göstermiştir.',
    'labels.executiveSummaryHighlights': 'En güçlü alanları Strategic Thinking, Problem Solving ve Leadership & Influence olarak öne çıkmaktadır.',
    'labels.fullReportSummary': 'Tüm yetkinlikler, 360° geri bildirimler ve gelişim önerileri.',
    'labels.sampleRole': 'Kıdemli Ürün Müdürü',
    'labels.registrationNumber': 'Sicil No',
    'labels.personName': 'Kişi Adı',
    'labels.email': 'Email',
    'labels.generalManagerAssistant': 'Genel Müdür Yardımcılığı',
    'labels.directorate': 'Direktörlük',
    'labels.management': 'Müdürlük',
    'labels.departmentLeadership': 'Departman/Şeflik',
    'labels.organizationTemplate': 'Organizasyon Template',
    'labels.sampleGeneralManagerAssistant': 'Örnek Genel Müdür Yardımcılığı',
    'labels.sampleDirectorate': 'Örnek Direktörlük',
    'labels.sampleManagement': 'Örnek Müdürlük',
    'labels.sampleDepartmentLeadership': 'Örnek Departman/Şeflik',
    'labels.sampleTitle': 'Örnek Unvan',
    'labels.samplePosition': 'Örnek Pozisyon',
    'labels.addOrganizationDesc': 'Organizasyon bilgilerini girin',
    'labels.editOrganizationDesc': 'Organizasyon bilgilerini güncelleyin',
    'labels.positionNotFound': 'Pozisyon bulunamadı',
    'labels.success': 'Başarılı!',
    'labels.error': 'Hata!',
    'labels.excelImport': 'Excel Import',
    'labels.uploadExcelFile': 'Excel Dosyası Yükle',
    'labels.selectOrDropExcel': 'Excel dosyasını seçin veya sürükleyin',
    'labels.selectedFile': 'Seçilen dosya',
    'labels.uploading': 'Yükleniyor...',
    'labels.excelUploading': 'Excel dosyası yükleniyor...',
    'labels.supportedFormats': '.xlsx, .xls formatları desteklenir',
    'labels.peopleTemplate': 'Kişiler Template',
    'labels.actions': 'İşlemler',
    'placeholders.registrationNumber': 'Lütfen Sicil No Giriniz',
    'placeholders.personName': 'Lütfen Kişi Adını Giriniz',
    'placeholders.email': 'Lütfen Email Giriniz',
    'placeholders.positionSearch': 'Pozisyon ara...',
    'placeholders.groupSearch': 'Grup adında akıllı arama yapın...',
    'placeholders.groupName': 'Grup adını giriniz',
    'placeholders.competencySearch': 'Yetkinlik adında akıllı arama yapın...',
    'placeholders.companySearch': 'Firma ara...',
    'placeholders.companyName': 'Firma adını giriniz',
    'placeholders.companyEmail': 'Firma e-postasını giriniz',
    'placeholders.gameSearch': "Firma adı ve fatura no'da akıllı arama yapın...",
    'placeholders.invoiceNo': 'Fatura numarasını giriniz',
    'placeholders.credit': 'Kredi miktarını giriniz',
    'placeholders.password': 'Şifre giriniz',
    'placeholders.newPasswordOptional': 'Yeni şifre giriniz (değiştirmek istemiyorsanız boş bırakın)',
    'placeholders.generalManagerAssistant': 'Genel Müdür Yardımcılığı girin',
    'placeholders.directorate': 'Direktörlük girin',
    'placeholders.management': 'Müdürlük girin',
    'placeholders.departmentLeadership': 'Departman/Şeflik girin',
    'placeholders.title': 'Unvan girin',
    'placeholders.position': 'Pozisyon girin',
    'buttons.uploadExcel': 'Excel Yükle',
    'buttons.downloadTemplate': 'Template İndir',
    'buttons.upload': 'Yükle',
    'buttons.previous': 'Önceki',
    'buttons.next': 'Sonraki',
    'buttons.no': 'Hayır',
    'buttons.addGroup': 'Yeni Grup Ekle',
    'buttons.updateGroup': 'Güncelle',
    'buttons.deleteGroup': 'Sil',
    'buttons.viewGroupDetails': 'Detayı Gör',
    'buttons.close': 'Kapat',
    'buttons.save': 'Kaydet',
    'buttons.viewInvoice': 'Faturayı Görüntüle',
    'buttons.view': 'Görüntüle',
    'buttons.moreCredits': 'Daha Fazla Kredi',
    'errors.authorizationListLoad': 'Yetkilendirme listesi yüklenemedi',
    'errors.authorizationListFetch': 'Yetkilendirme listesi alınamadı',
    'errors.authorizationLoad': 'Yetkilendirmeler yüklenirken bir hata oluştu',
    'errors.organizationListFetch': 'Organizasyon listesi alınamadı',
    'errors.dataLoadFailed': 'Veriler yüklenemedi',
    'errors.competencyAddFailed': 'Yetkinlik eklenemedi',
    'errors.competencyAddError': 'Yetkinlik eklenirken bir hata oluştu',
    'errors.competencyIdMissing': 'Yetkinlik oluşturuldu ancak ID alınamadı',
    'errors.competencyUpdateFailed': 'Yetkinlik güncellenemedi',
    'errors.competencyUpdateError': 'Yetkinlik güncellenirken bir hata oluştu',
    'errors.competencyDeleteFailed': 'Bazı yetkinlikler silinemedi',
    'errors.competencyDeleteError': 'Yetkinlik silinirken bir hata oluştu',
    'errors.importFailed': 'Import işlemi başarısız!',
    'errors.importError': 'Import işlemi sırasında bir hata oluştu',
    'errors.serverError': 'Sunucu hatası',
    'errors.tryAgain': 'Lütfen tekrar deneyin',
    'errors.groupListLoad': 'Grup listesi yüklenemedi',
    'errors.groupListFetch': 'Grup listesi alınamadı',
    'errors.groupsLoad': 'Gruplar yüklenirken bir hata oluştu',
    'errors.groupDataFetch': 'Grup verileri alınamadı',
    'errors.selectGroupToDelete': 'Lütfen silmek istediğiniz kayıtları seçiniz!',
    'errors.enterGroupName': 'Lütfen grup adını giriniz!',
    'errors.selectOrgOrPerson': 'Lütfen en az bir organizasyon veya kişi seçiniz!',
    'errors.selectPlanet': 'Lütfen en az bir gezegen seçiniz!',
    'errors.groupSaveFailed': 'Grup kaydedilemedi',
    'errors.groupSaveError': 'Grup kaydedilirken bir hata oluştu',
    'errors.groupDeleteFailed': 'Grup silinemedi',
    'errors.groupDeleteError': 'Grup silinirken bir hata oluştu',
    'errors.selectOrganization': 'Lütfen bir organizasyon seçin!',
    'errors.organizationAlreadySelected': 'Bu organizasyon zaten seçilmiş!',
    'errors.matchingPersonsFetch': 'Eşleşen kişiler alınamadı',
    'errors.pdfCreateFailed': 'PDF oluşturulurken bir hata oluştu',
    'errors.adminAddError': 'Admin eklenirken bir hata oluştu',
    'errors.adminUpdateError': 'Admin güncellenirken bir hata oluştu',
    'errors.adminDeleteError': 'Admin silinirken bir hata oluştu',
    'errors.companyAddError': 'Firma eklenirken bir hata oluştu',
    'errors.companyUpdateError': 'Firma güncellenirken bir hata oluştu',
    'errors.companyDeleteError': 'Firma silinirken bir hata oluştu',
    'errors.gameDataFetch': 'Oyun verileri alınamadı',
    'errors.invoiceNotFound': 'Bu oyun için fatura dosyası bulunamadı!',
    'errors.invoicePreviewError': 'Fatura görüntülenirken bir hata oluştu',
    'errors.companyNameRequired': 'Firma adı zorunludur!',
    'errors.selectCompany': 'Lütfen firma seçiniz!',
    'errors.invoiceRequired': 'Fatura numarası zorunludur!',
    'errors.creditRequired': 'Geçerli bir kredi miktarı giriniz!',
    'errors.invoiceFileRequired': 'Fatura dosyası zorunludur!',
    'errors.gameAddError': 'Oyun eklenirken bir hata oluştu',
    'errors.gameUpdateFailed': 'Oyun güncellenemedi',
    'errors.gameUpdateError': 'Oyun güncellenirken bir hata oluştu',
    'errors.gameDeleteError': 'Oyun silinirken bir hata oluştu',
    'errors.selectRecordsToDelete': 'Lütfen silmek istediğiniz kayıtları seçiniz!',
    'errors.bulkDeleteFailed': 'Toplu silme işlemi sırasında bir hata oluştu',
    'errors.enterRegistrationNumber': 'Lütfen sicil numarasını giriniz!',
    'errors.enterPersonName': 'Lütfen kişi adını giriniz!',
    'errors.enterEmail': 'Lütfen email adresini giriniz!',
    'errors.selectPosition': 'Lütfen pozisyon seçiniz!',
    'errors.authorizationAddFailed': 'Yetkilendirme eklenemedi',
    'errors.authorizationAddError': 'Yetkilendirme eklenirken bir hata oluştu',
    'errors.authorizationUpdateFailed': 'Yetkilendirme güncellenemedi',
    'errors.authorizationUpdateError': 'Yetkilendirme güncellenirken bir hata oluştu',
    'errors.deleteFailed': 'Silme işlemi başarısız',
    'errors.authorizationDeleteError': 'Yetkilendirme silinirken bir hata oluştu',
    'errors.templateDownloadError': 'Template indirilirken bir hata oluştu!',
    'errors.selectExcelFirst': 'Lütfen önce bir Excel dosyası seçin!',
    'errors.noPermissionRelogin': 'Yetkiniz bulunmuyor. Lütfen tekrar giriş yapın.',
    'errors.fileTooLarge': 'Dosya çok büyük. Lütfen daha küçük bir dosya seçin.',
    'errors.invalidFileFormat': 'Dosya formatı hatalı. Lütfen geçerli bir Excel dosyası seçin.',
    'errors.fileUploadError': 'Dosya yüklenirken bir hata oluştu.',
    'errors.onlyExcelAllowed': 'Lütfen sadece Excel dosyası (.xlsx, .xls) seçin!',
    'messages.authorizationAdded': 'Yetkilendirme başarıyla eklendi!',
    'messages.authorizationUpdated': 'Yetkilendirme başarıyla güncellendi!',
    'messages.authorizationDeleted': 'Yetkilendirme başarıyla silindi!',
    'messages.templateDownloadSuccess': 'Excel template başarıyla indirildi!',
    'messages.groupCreated': 'Grup başarıyla oluşturuldu!',
    'messages.groupUpdated': 'Grup başarıyla güncellendi!',
    'messages.groupDeleted': 'Grup başarıyla silindi!',
    'messages.noMatchingPositions': 'Seçilen organizasyonlarda eşleşen pozisyon bulunamadı.',
    'messages.personsAutoAdded': 'kişisi otomatik olarak eklendi!',
    'messages.gameAdded': 'Oyun başarıyla eklendi!',
    'messages.gameUpdated': 'Oyun başarıyla güncellendi!',
    'messages.gameDeleted': 'Oyun başarıyla silindi!',
    'titles.addOrganization': 'Yeni Organizasyon Ekle',
    'titles.editOrganization': 'Organizasyon Düzenle',
    'titles.deleteOrganization': 'Organizasyonu Sil',
    'titles.addCompetency': 'Yetkinlik Ekle',
    'titles.editCompetency': 'Yetkinlik Düzenle',
    'titles.deleteCompetency': 'Yetkinlik Sil',
    'titles.paymentHistory': 'Geçmiş Ödemeler',
    'titles.editGroup': 'Grup Düzenle',
    'titles.deleteGroup': 'Grup Sil',
    'titles.addAdmin': 'Admin Ekle',
    'titles.deleteAdmin': 'Admin Sil',
    'titles.editGame': 'Oyun Düzenle',
    'titles.viewInvoice': 'Fatura Görüntüle',
    'titles.editCompany': 'Firma Düzenle',
    'titles.adminPanel': 'Genel Takip Sistemi',
    'titles.authorization': 'Kişiler',
    'titles.organization': 'Organizasyon',
    'titles.grouping': 'Gruplama',
    'titles.defineCompanyAdmin': 'Firma Admini Tanımlama',
    'titles.competencySettings': 'Yetkinlik Ayarları',
    'titles.subscriptionSettings': 'Abonelik Ayarları',
    'titles.gameSend': 'Oyun Gönderme',
    'titles.scriptFiles': 'Komut Dosyaları',
    'titles.gameManagement': 'Oyun Tanımlama',
    'titles.companyIdentification': 'Firma Tanımlama',
    'competency.customerFocus': 'Müşteri Odaklılık',
    'competency.uncertainty': 'Uyumluluk ve Dayanıklılık',
    'competency.ie': 'İnsanları Etkileme',
    'competency.idik': 'Güven Veren İşbirliği ve Sinerji',
    'competency.customerFocus.desc': 'Müşteri ihtiyaçlarını anlama ve çözüm üretme',
    'competency.uncertainty.desc': 'Belirsizliklerle başa çıkma ve dayanıklılık gösterme',
    'competency.ie.desc': 'İkna, etkileme ve yönlendirme becerileri',
    'competency.idik.desc': 'Ekip içinde güven, işbirliği ve uyum oluşturma',
    'status.completed': 'Tamamlandı',
    'status.inProgress': 'Oyun Devam Ediyor',
    'status.expired': 'Süresi Doldu',
    'status.sent': 'Gönderildi',
    'status.active': 'Aktif',
    'status.passive': 'Pasif',
    'labels.currentReport': 'Güncel Değerlendirme Özeti',
    'labels.fullReport': 'Tam Değerlendirme Raporu',
    'buttons.viewReport': 'Raporu Görüntüle',
    'buttons.downloadPdf': 'PDF İndir',
    'buttons.share': 'Paylaş',
    'labels.executiveSummarySubtitle': 'Q4 2024 değerlendirme sonuçlarının üst düzey özeti',
    'labels.generalSummary': 'Genel Özet',
    'labels.strengths': 'Güçlü Yönler',
    'labels.developmentAreas': 'Gelişim Alanları',
    'labels.competencyDetailsHeader': 'Yetkinlik Detayları',
    'labels.competencySelect': 'Yetkinlik Seç:',
    'labels.generalEvaluation': 'Genel Değerlendirme',
    'labels.strengthsDev': 'Güçlü Yönler & Gelişim Alanları',
    'labels.interviewQuestions': 'Mülakat Soruları',
    'labels.developmentPlan': 'Gelişim Planı',
    'labels.whyTheseQuestions': 'Neden Bu Sorular?',
    'labels.developmentArea': 'Gelişim Alanı',
    'labels.interviewQuestion': 'Mülakat Sorusu',
    'labels.followUpQuestion': 'Devam Sorusu',
    'labels.reportAccessTitle': 'Rapor Erişimi',
    'labels.reportAccessSubtitle': 'Tam raporu görüntüleyin, indirin veya paylaşın',
    'labels.viewOnline': 'Raporu Tarayıcıda Görüntüle',
    'labels.downloadReport': 'PDF İndir',
    'labels.shareReport': 'Raporu Paylaş',
    'labels.viewOnlineDesc': 'Raporu tarayıcıda görüntüle',
    'labels.downloadPdfDesc': 'Cihazınıza indirin',
    'labels.shareReportDesc': 'Paydaşlarla paylaşın',
    'labels.aiAssistantSoon': 'AI Asistan Yakında',
    'placeholders.searchAllColumns': 'Tüm sütunlarda akıllı arama yapın...',
    'buttons.cancel': 'İptal',
    'buttons.add': 'Ekle',
    'buttons.update': 'Güncelle',
    'buttons.delete': 'Sil',
    'buttons.bulkDelete': 'Toplu Sil',
    'buttons.confirmDelete': 'Evet, Sil',
    'statuses.adding': 'Ekleniyor...',
    'statuses.updating': 'Güncelleniyor...',
    'statuses.deleting': 'Siliniyor...',
    'statuses.saving': 'Kaydediliyor...',
    'titles.addPerson': 'Kişi Ekle',
    'titles.deletePerson': 'Kişiyi Sil',
    'titles.bulkDelete': 'Toplu Silme',
    'titles.filtering': 'Filtreleme',
    'labels.title': 'Unvan',
    'labels.position': 'Pozisyon',
    'labels.noRecords': 'Kayıt bulunamadı',
    'buttons.clearFilters': 'Filtreleri Temizle',
    'buttons.applyFilters': 'Filtreleri Uygula',
    'buttons.switchToEnglish': 'İngilizceye geç',
    'buttons.switchToTurkish': 'Türkçeye geç'
  },
  en: {
    'nav.main': 'Main Menu',
    'nav.settings': 'Settings',
    'nav.companySettings': 'Company Settings',
    'nav.otherSettings': 'Other Settings',
    'nav.superAdminSettings': 'Super Admin Settings',
    'nav.logout': 'Sign Out',
    'menu.dashboard': 'Dashboard',
    'menu.admin': 'General Tracking',
    'menu.personResults': 'Detailed Person Results',
    'menu.personScores': 'Person Scores',
    'menu.gameSend': 'Send Game',
    'menu.usageSummary': 'Game Usage Summary',
    'menu.companySetup': 'Company Setup',
    'menu.companyAdminSetup': 'Company Admin Setup',
    'menu.gameSetup': 'Game Setup',
    'menu.organization': 'Organization',
    'menu.competencySettings': 'Competency Settings',
    'menu.scriptFiles': 'Script Files',
    'breadcrumbs.evaluations': 'Evaluations',
    'breadcrumbs.personResults': 'Person Results',
    'breadcrumbs.reportDetails': 'Report Details',
    'titles.personResults': 'Person Evaluation Results',
    'titles.personReport': 'Comprehensive Assessment Report',
    'titles.personResultsSection': 'Person Results',
    'titles.personScores': 'Person Scores',
    'tabs.executiveSummary': 'Executive Summary',
    'tabs.competencyDetails': 'Competency Details',
    'tabs.reportAccess': 'Report Access',
    'tabs.aiAssistant': 'AI Assistant',
    'tabs.trend': 'Trend Analysis',
    'tabs.summary': 'Summary',
    'tabs.fullReport': 'Full Report',
    'labels.currentEvaluation': 'Latest Evaluation',
    'labels.completion': 'Completed',
    'labels.competencyStatus': 'Current Competency Status',
    'labels.competencyStatusDesc': 'Latest evaluation and benchmark results',
    'labels.reportDetails': 'Report Details',
    'labels.evaluationDate': 'Evaluation Date',
    'labels.trendAnalysis': 'Competency Trend Analysis',
    'labels.lastThreeResults': 'Results from the last 3 evaluations',
    'labels.selectCompetency': 'Select Competency',
    'labels.trendTip': 'Select a competency to view the trend on the right panel',
    'labels.currentTag': 'Current',
    'labels.comprehensiveAssessment': 'Q4 2024 Comprehensive Assessment',
    'labels.developingCompetency': 'Developing Competency',
    'titles.dashboard': 'Dashboard',
    'labels.gameSendStatus': 'Game Send Status',
    'labels.competencyDistributions': 'Competency Score Distributions',
    'labels.competencySelection': 'Competency Selection',
    'labels.competencyScore': 'Competency Score',
    'labels.peopleEvaluated': 'Number of People Evaluated',
    'labels.totalGamesSent': 'Total Games Sent',
    'labels.competencyGameDistribution': 'Game Distribution by Competency',
    'buttons.filter': 'Filter',
    'buttons.refresh': 'Refresh',
    'buttons.downloadResults': 'Download Results',
    'labels.loadingResults': 'Loading results...',
    'labels.noResults': 'No results found.',
    'labels.completionDate': 'Completion Date',
    'labels.detail': 'Detail',
    'labels.goToPersonResults': 'Go to person results',
    'labels.nameSurname': 'Full Name',
    'labels.pdfPreview': 'PDF Preview',
    'labels.pdfLoading': 'Loading PDF...',
    'labels.notEnoughData': 'Not enough data',
    'labels.authorizationsLoading': 'Loading authorizations...',
    'labels.organizationsLoading': 'Loading organizations...',
    'labels.groupsLoading': 'Loading groups...',
    'labels.groups': 'Groups',
    'labels.groupName': 'Group Name',
    'labels.status': 'Status',
    'labels.details': 'Details',
    'labels.competenciesLoading': 'Loading competencies...',
    'labels.competenciesEmpty': 'No competencies yet',
    'labels.selection': 'Selection',
    'labels.selectPosition': 'Select position',
    'labels.startDate': 'Start Date',
    'labels.noData': 'No data',
    'labels.totalCredits': 'Total Credits',
    'labels.credits': 'Credits',
    'labels.fee': 'Fee',
    'labels.monthlyFeeSample': '$120 /Monthly',
    'labels.creditUsage': 'Credit Usage',
    'labels.usageSinceSample': 'Since 10/04/2025 12:16',
    'labels.remainingUsage': 'Remaining Usage',
    'labels.usedUsage': 'Used Usage',
    'labels.date': 'Date',
    'labels.invoiceNo': 'Invoice No',
    'labels.credit': 'Credit',
    'labels.loading': 'Loading...',
    'labels.noGameData': 'No game data available yet',
    'labels.customerFocusMin': 'Customer Focus Min Value',
    'labels.customerFocusMax': 'Customer Focus Max Value',
    'labels.uncertaintyMin': 'Adaptability & Resilience Min Value',
    'labels.uncertaintyMax': 'Adaptability & Resilience Max Value',
    'labels.ieMin': 'Influencing Others Min Value',
    'labels.ieMax': 'Influencing Others Max Value',
    'labels.idikMin': 'Trusting Collaboration & Synergy Min Value',
    'labels.idikMax': 'Trusting Collaboration & Synergy Max Value',
    'labels.competencySettingsSheet': 'Competency Settings',
    'labels.competencySettingsTemplateFile': 'competency_settings_template.xlsx',
    'labels.deleteCompetencyConfirm': 'Are you sure you want to delete these competencies?',
    'labels.competencyDeleted': 'competencies deleted successfully!',
    'labels.groupInfo': 'Group Info',
    'labels.groupDetailsTitle': 'Group Details',
    'labels.organizationSearchPlaceholder': 'Search organization',
    'labels.personSearchPlaceholder': 'Search person',
    'labels.planetSearchPlaceholder': 'Search planet',
    'labels.organizationNotFound': 'Organization not found',
    'labels.personNotFound': 'Person not found',
    'labels.planetNotFound': 'Planet not found',
    'labels.viewDetails': 'View Details',
    'labels.bulkDelete': 'Bulk Delete',
    'labels.groupsEmpty': 'No groups yet',
    'labels.groupsNotFound': 'No groups match your search criteria',
    'labels.groupDetailsSubtitle': 'Update group info and manage organizations, people, and planets',
    'labels.planetVenus': 'Venus',
    'labels.planetTitan': 'Titan',
    'labels.planets': 'Planets',
    'labels.createdAt': 'Created At',
    'labels.unknown': 'Unknown',
    'labels.user': 'User',
    'labels.about': 'About',
    'labels.createGroupDesc': 'Create a new group and assign organizations, people, and planets',
    'labels.noOrganizationSelected': 'No organization selected yet',
    'labels.noPersonSelected': 'No person selected yet',
    'labels.noPlanetSelected': 'No planet selected yet',
    'labels.company': 'Company',
    'labels.companyName': 'Company Name',
    'labels.companyEmail': 'Company Email',
    'labels.gameDetailsLoading': 'Loading game details...',
    'labels.invoiceLoading': 'Loading invoice...',
    'labels.uploadInvoice': 'Upload Invoice',
    'labels.uploadInvoiceOptional': 'Upload Invoice (Optional)',
    'labels.deleteGameConfirm': 'Are you sure you want to delete this game?',
    'labels.companySelect': 'Select company',
    'labels.companyNotFound': 'Company not found',
    'labels.loadingData': 'Loading data...',
    'labels.password': 'Password',
    'labels.newPasswordOptional': 'New Password (Optional)',
    'labels.deleteAdminConfirm': 'Are you sure you want to delete this admin?',
    'labels.actionIrreversible': 'This action cannot be undone!',
    'labels.assessmentReport': 'AssessmentReport',
    'labels.participation': 'Participation',
    'labels.sampleParticipation': 'Jan 2020',
    'labels.previousPeriodChange': 'Change vs previous period: +0.7',
    'labels.positiveGrowth': '75% positive improvement',
    'labels.percentileRank': 'Percentile Rank',
    'labels.companyOverall': 'Company-wide',
    'labels.executiveSummarySample': 'Sarah Johnson delivered a strong performance in the Q4 2024 evaluation with an overall score of 8.4/10.',
    'labels.executiveSummaryHighlights': 'Top strengths include Strategic Thinking, Problem Solving, and Leadership & Influence.',
    'labels.fullReportSummary': 'All competencies, 360° feedback, and development recommendations.',
    'labels.sampleRole': 'Senior Product Manager',
    'labels.registrationNumber': 'Registration No',
    'labels.personName': 'Person Name',
    'labels.email': 'Email',
    'labels.generalManagerAssistant': 'General Manager Assistant',
    'labels.directorate': 'Directorate',
    'labels.management': 'Management',
    'labels.departmentLeadership': 'Department/Team Lead',
    'labels.organizationTemplate': 'Organization Template',
    'labels.sampleGeneralManagerAssistant': 'Sample General Manager Assistant',
    'labels.sampleDirectorate': 'Sample Directorate',
    'labels.sampleManagement': 'Sample Management',
    'labels.sampleDepartmentLeadership': 'Sample Department/Team Lead',
    'labels.sampleTitle': 'Sample Title',
    'labels.samplePosition': 'Sample Position',
    'labels.addOrganizationDesc': 'Enter organization details',
    'labels.editOrganizationDesc': 'Update organization details',
    'labels.positionNotFound': 'Position not found',
    'labels.success': 'Success!',
    'labels.error': 'Error!',
    'labels.excelImport': 'Excel Import',
    'labels.uploadExcelFile': 'Upload Excel File',
    'labels.selectOrDropExcel': 'Select or drag the Excel file here',
    'labels.selectedFile': 'Selected file',
    'labels.uploading': 'Uploading...',
    'labels.excelUploading': 'Uploading Excel file...',
    'labels.supportedFormats': '.xlsx, .xls formats supported',
    'labels.peopleTemplate': 'People Template',
    'labels.actions': 'Actions',
    'placeholders.registrationNumber': 'Please enter registration number',
    'placeholders.personName': 'Please enter person name',
    'placeholders.email': 'Please enter email',
    'placeholders.positionSearch': 'Search position...',
    'placeholders.groupSearch': 'Search by group name...',
    'placeholders.groupName': 'Enter group name',
    'placeholders.competencySearch': 'Search by competency name...',
    'placeholders.companySearch': 'Search company...',
    'placeholders.companyName': 'Enter company name',
    'placeholders.companyEmail': 'Enter company email',
    'placeholders.gameSearch': 'Search by company name or invoice number...',
    'placeholders.invoiceNo': 'Enter invoice number',
    'placeholders.credit': 'Enter credit amount',
    'placeholders.password': 'Enter password',
    'placeholders.newPasswordOptional': 'Enter a new password (leave blank to keep current)',
    'placeholders.generalManagerAssistant': 'Enter general manager assistant',
    'placeholders.directorate': 'Enter directorate',
    'placeholders.management': 'Enter management',
    'placeholders.departmentLeadership': 'Enter department/team lead',
    'placeholders.title': 'Enter title',
    'placeholders.position': 'Enter position',
    'buttons.uploadExcel': 'Upload Excel',
    'buttons.downloadTemplate': 'Download Template',
    'buttons.upload': 'Upload',
    'buttons.previous': 'Previous',
    'buttons.next': 'Next',
    'buttons.no': 'No',
    'buttons.addGroup': 'Add New Group',
    'buttons.updateGroup': 'Update',
    'buttons.deleteGroup': 'Delete',
    'buttons.viewGroupDetails': 'View Details',
    'buttons.close': 'Close',
    'buttons.save': 'Save',
    'buttons.viewInvoice': 'View Invoice',
    'buttons.view': 'View',
    'buttons.moreCredits': 'More Credits',
    'errors.authorizationListLoad': 'Authorization list could not be loaded',
    'errors.authorizationListFetch': 'Authorization list could not be fetched',
    'errors.authorizationLoad': 'An error occurred while loading authorizations',
    'errors.organizationListFetch': 'Organization list could not be fetched',
    'errors.dataLoadFailed': 'Data could not be loaded',
    'errors.competencyAddFailed': 'Competency could not be added',
    'errors.competencyAddError': 'An error occurred while adding competency',
    'errors.competencyIdMissing': 'Competency created but no ID returned',
    'errors.competencyUpdateFailed': 'Competency could not be updated',
    'errors.competencyUpdateError': 'An error occurred while updating competency',
    'errors.competencyDeleteFailed': 'Some competencies could not be deleted',
    'errors.competencyDeleteError': 'An error occurred while deleting competency',
    'errors.importFailed': 'Import failed!',
    'errors.importError': 'An error occurred during import',
    'errors.serverError': 'Server error',
    'errors.tryAgain': 'Please try again',
    'errors.groupListLoad': 'Group list could not be loaded',
    'errors.groupListFetch': 'Group list could not be fetched',
    'errors.groupsLoad': 'An error occurred while loading groups',
    'errors.groupDataFetch': 'Group data could not be fetched',
    'errors.selectGroupToDelete': 'Please select the records you want to delete!',
    'errors.enterGroupName': 'Please enter group name!',
    'errors.selectOrgOrPerson': 'Please select at least one organization or person!',
    'errors.selectPlanet': 'Please select at least one planet!',
    'errors.groupSaveFailed': 'Group could not be saved',
    'errors.groupSaveError': 'An error occurred while saving the group',
    'errors.groupDeleteFailed': 'Group could not be deleted',
    'errors.groupDeleteError': 'An error occurred while deleting the group',
    'errors.selectOrganization': 'Please select an organization!',
    'errors.organizationAlreadySelected': 'This organization is already selected!',
    'errors.matchingPersonsFetch': 'Matching people could not be fetched',
    'errors.pdfCreateFailed': 'An error occurred while creating the PDF',
    'errors.adminAddError': 'An error occurred while adding admin',
    'errors.adminUpdateError': 'An error occurred while updating admin',
    'errors.adminDeleteError': 'An error occurred while deleting admin',
    'errors.companyAddError': 'An error occurred while adding company',
    'errors.companyUpdateError': 'An error occurred while updating company',
    'errors.companyDeleteError': 'An error occurred while deleting company',
    'errors.gameDataFetch': 'Game data could not be fetched',
    'errors.invoiceNotFound': 'No invoice file found for this game!',
    'errors.invoicePreviewError': 'An error occurred while viewing the invoice',
    'errors.companyNameRequired': 'Company name is required!',
    'errors.selectCompany': 'Please select a company!',
    'errors.invoiceRequired': 'Invoice number is required!',
    'errors.creditRequired': 'Please enter a valid credit amount!',
    'errors.invoiceFileRequired': 'Invoice file is required!',
    'errors.gameAddError': 'An error occurred while adding the game',
    'errors.gameUpdateFailed': 'Game could not be updated',
    'errors.gameUpdateError': 'An error occurred while updating the game',
    'errors.gameDeleteError': 'An error occurred while deleting the game',
    'errors.selectRecordsToDelete': 'Please select the records you want to delete!',
    'errors.bulkDeleteFailed': 'An error occurred during bulk delete',
    'errors.enterRegistrationNumber': 'Please enter registration number!',
    'errors.enterPersonName': 'Please enter person name!',
    'errors.enterEmail': 'Please enter email address!',
    'errors.selectPosition': 'Please select a position!',
    'errors.authorizationAddFailed': 'Authorization could not be added',
    'errors.authorizationAddError': 'An error occurred while adding authorization',
    'errors.authorizationUpdateFailed': 'Authorization could not be updated',
    'errors.authorizationUpdateError': 'An error occurred while updating authorization',
    'errors.deleteFailed': 'Delete failed',
    'errors.authorizationDeleteError': 'An error occurred while deleting authorization',
    'errors.templateDownloadError': 'An error occurred while downloading the template!',
    'errors.selectExcelFirst': 'Please select an Excel file first!',
    'errors.noPermissionRelogin': 'You do not have permission. Please log in again.',
    'errors.fileTooLarge': 'File is too large. Please select a smaller file.',
    'errors.invalidFileFormat': 'Invalid file format. Please select a valid Excel file.',
    'errors.fileUploadError': 'An error occurred while uploading the file.',
    'errors.onlyExcelAllowed': 'Please select only Excel files (.xlsx, .xls)!',
    'messages.authorizationAdded': 'Authorization added successfully!',
    'messages.authorizationUpdated': 'Authorization updated successfully!',
    'messages.authorizationDeleted': 'Authorization deleted successfully!',
    'messages.templateDownloadSuccess': 'Excel template downloaded successfully!',
    'messages.gameAdded': 'Game added successfully!',
    'messages.gameUpdated': 'Game updated successfully!',
    'messages.gameDeleted': 'Game deleted successfully!',
    'messages.groupCreated': 'Group created successfully!',
    'messages.groupUpdated': 'Group updated successfully!',
    'messages.groupDeleted': 'Group deleted successfully!',
    'messages.noMatchingPositions': 'No matching positions found in the selected organizations.',
    'messages.personsAutoAdded': 'people were added automatically!',
    'titles.addOrganization': 'Add New Organization',
    'titles.editOrganization': 'Edit Organization',
    'titles.deleteOrganization': 'Delete Organization',
    'titles.addCompetency': 'Add Competency',
    'titles.editCompetency': 'Edit Competency',
    'titles.deleteCompetency': 'Delete Competency',
    'titles.paymentHistory': 'Payment History',
    'titles.editGroup': 'Edit Group',
    'titles.deleteGroup': 'Delete Group',
    'titles.addAdmin': 'Add Admin',
    'titles.deleteAdmin': 'Delete Admin',
    'titles.editCompany': 'Edit Company',
    'titles.editGame': 'Edit Game',
    'titles.viewInvoice': 'View Invoice',
    'titles.adminPanel': 'General Tracking',
    'titles.authorization': 'People',
    'titles.organization': 'Organization',
    'titles.grouping': 'Grouping',
    'titles.defineCompanyAdmin': 'Define Company Admin',
    'titles.competencySettings': 'Competency Settings',
    'titles.subscriptionSettings': 'Subscription Settings',
    'titles.gameSend': 'Send Game',
    'titles.scriptFiles': 'Script Files',
    'titles.gameManagement': 'Game Management',
    'titles.companyIdentification': 'Company Identification',
    'competency.customerFocus': 'Customer Focus',
    'competency.uncertainty': 'Adaptability & Resilience',
    'competency.ie': 'Influencing Others',
    'competency.idik': 'Trusting Collaboration & Synergy',
    'competency.customerFocus.desc': 'Understanding customer needs and delivering solutions',
    'competency.uncertainty.desc': 'Handling uncertainty and demonstrating resilience',
    'competency.ie.desc': 'Persuasion, influence, and guidance skills',
    'competency.idik.desc': 'Building trust, collaboration, and alignment within teams',
    'status.completed': 'Completed',
    'status.inProgress': 'In Progress',
    'status.expired': 'Expired',
    'status.sent': 'Sent',
    'status.active': 'Active',
    'status.passive': 'Passive',
    'labels.currentReport': 'Current Evaluation Summary',
    'labels.fullReport': 'Full Assessment Report',
    'buttons.viewReport': 'View Report',
    'buttons.downloadPdf': 'Download PDF',
    'buttons.share': 'Share',
    'labels.executiveSummarySubtitle': 'High-level summary of Q4 2024 evaluation results',
    'labels.generalSummary': 'General Summary',
    'labels.strengths': 'Strengths',
    'labels.developmentAreas': 'Development Areas',
    'labels.competencyDetailsHeader': 'Competency Details',
    'labels.competencySelect': 'Select Competency:',
    'labels.generalEvaluation': 'General Evaluation',
    'labels.strengthsDev': 'Strengths & Development Areas',
    'labels.interviewQuestions': 'Interview Questions',
    'labels.developmentPlan': 'Development Plan',
    'labels.whyTheseQuestions': 'Why These Questions?',
    'labels.developmentArea': 'Development Area',
    'labels.interviewQuestion': 'Interview Question',
    'labels.followUpQuestion': 'Follow-up Question',
    'labels.reportAccessTitle': 'Report Access',
    'labels.reportAccessSubtitle': 'View, download, or share the full report',
    'labels.viewOnline': 'View Report Online',
    'labels.downloadReport': 'Download PDF',
    'labels.shareReport': 'Share Report',
    'labels.viewOnlineDesc': 'View the report in your browser',
    'labels.downloadPdfDesc': 'Download to your device',
    'labels.shareReportDesc': 'Share with stakeholders',
    'labels.aiAssistantSoon': 'AI Assistant Coming Soon',
    'placeholders.searchAllColumns': 'Search across all columns...',
    'buttons.cancel': 'Cancel',
    'buttons.add': 'Add',
    'buttons.update': 'Update',
    'buttons.delete': 'Delete',
    'buttons.bulkDelete': 'Bulk Delete',
    'buttons.confirmDelete': 'Yes, Delete',
    'statuses.adding': 'Adding...',
    'statuses.updating': 'Updating...',
    'statuses.deleting': 'Deleting...',
    'statuses.saving': 'Saving...',
    'titles.addPerson': 'Add Person',
    'titles.deletePerson': 'Delete Person',
    'titles.bulkDelete': 'Bulk Delete',
    'titles.filtering': 'Filtering',
    'labels.title': 'Title',
    'labels.position': 'Position',
    'labels.noRecords': 'No records found',
    'buttons.clearFilters': 'Clear Filters',
    'buttons.applyFilters': 'Apply Filters',
    'buttons.switchToEnglish': 'Switch to English',
    'buttons.switchToTurkish': 'Switch to Turkish'
  }
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('appLanguage');
    return stored === 'en' ? 'en' : 'tr';
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => {
    const t = (key: string) => translations[language][key] || translations.tr[key] || key;
    return {
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((prev) => (prev === 'tr' ? 'en' : 'tr')),
      t
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
