import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Language = 'tr' | 'en';

type LanguageContextValue = {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  tr: {
    'nav.main': 'Ana Menü',
    'nav.settings': 'Ayarlar',
    'nav.companySettings': 'Firma Ayarları',
    'nav.logout': 'Çıkış Yap',
    'menu.dashboard': 'Kontrol Paneli',
    'menu.admin': 'Genel Takip Sistemi',
    'menu.personResults': 'Detaylı Kişi Sonuçları',
    'menu.personScores': 'Kişi Skorları Sayfası',
    'menu.gameSend': 'Oyun Gönder',
    'menu.usageSummary': 'Oyun Kullanım Özeti',
    'menu.companySetup': 'Firma Tanımlama',
    'menu.companyAdminSetup': 'Firma Admini Tanımlama',
    'menu.gameSetup': 'Oyun Tanımlama',
    'menu.organization': 'Organizasyon',
    'menu.competencySettings': 'Yetkinlik Ayarları',
    'menu.scriptFiles': 'Komut Dosyaları',
    'titles.personResults': 'Detaylı Kişi Sonuçları',
    'titles.personReport': 'Kapsamlı Değerlendirme Raporu',
    'titles.personResultsSection': 'Kişi Sonuçları',
    'titles.personScores': 'Kişi Skorları Sayfası',
    'tabs.executiveSummary': 'Yönetici Özeti',
    'tabs.competencyDetails': 'Yetkinlik Detayları',
    'tabs.reportAccess': 'Rapor Erişimi',
    'tabs.aiAssistant': 'AI Asistan',
    'tabs.trend': 'Trend Analizi',
    'tabs.summary': 'Özet',
    'tabs.fullReport': 'Tam Rapor',
    'labels.currentEvaluation': 'Son Değerlendirme',
    'labels.completion': 'Tamamlandı',
    'labels.competencyStatus': 'Mevcut Yetkinlik Durumu',
    'labels.competencyStatusDesc': 'Son değerlendirme ve benchmark sonuçları',
    'labels.reportDetails': 'Rapor Detayları',
    'labels.evaluationDate': 'Değerlendirme Tarihi',
    'labels.trendAnalysis': 'Yetkinlik Trend Analizi',
    'labels.lastThreeResults': 'Son 3 değerlendirme sonucu',
    'labels.selectCompetency': 'Yetkinlik Seç',
    'labels.trendTip': 'Sağ panelde trend görmek için bir yetkinlik seçin',
    'labels.currentTag': 'Güncel',
    'labels.comprehensiveAssessment': 'Q4 2024 Kapsamlı Değerlendirme',
    'labels.developingCompetency': 'Gelişen Yetkinlik',
    'titles.dashboard': 'Kontrol Paneli',
    'labels.gameSendStatus': 'Oyun Gönderim Durumu',
    'labels.competencyDistributions': 'Yetkinlik Skor Dağılımları',
    'labels.competencySelection': 'Yetkinlik Seçimi',
    'labels.competencyScore': 'Yetkinlik Puanı',
    'labels.peopleEvaluated': 'Değerlendirme Gönderilen Kişi Sayısı',
    'labels.peopleCount': 'Kişi Sayısı',
    'labels.totalGamesSent': 'Toplam Gönderilen Oyun Sayısı',
    'labels.competencyGameDistribution': 'Yetkinliğe Göre Oyun Dağılımı',
    'buttons.filter': 'Filtrele',
    'buttons.refresh': 'Yenile',
    'buttons.downloadResults': 'Sonuçları İndir',
    'labels.loadingResults': 'Sonuçlar yükleniyor...',
    'labels.noResults': 'Gösterilecek sonuç bulunamadı.',
    'labels.completionDate': 'Tamamlanma Tarihi',
    'labels.detail': 'Detay',
    'labels.goToPersonResults': 'Detaylı Kişi Sonucuna Git',
    'labels.nameSurname': 'Ad Soyad',
    'labels.sentDate': 'Gönderim Tarihi',
    'labels.codeExpiryDate': 'Kod Geçerlilik Tarihi',
    'labels.reportExpiryDate': 'Rapor Geçerlilik Tarihi',
    'labels.evaluationReportFile': 'ANDRON_DeğerlendirmeRaporu',
    'labels.downloadPdf': 'PDF İndir',
    'labels.downloadExcel': 'Excel İndir',
    'labels.downloadWord': 'Word İndir',
    'labels.viewAnswers': 'Cevapları Görüntüle',
    'labels.hasUnplayedGame': 'Oynanmamış oyun var',
    'labels.gameAnswersTitle': 'Oyun Cevapları',
    'labels.gameInfo': 'Oyun Bilgileri',
    'labels.code': 'Kod',
    'labels.reportId': 'Rapor ID',
    'labels.question': 'Soru',
    'labels.selectedAnswer1': 'Seçilen Cevap 1',
    'labels.selectedAnswer2': 'Seçilen Cevap 2',
    'labels.subCategory': 'Alt Kategori',
    'labels.preview': 'Önizleme',
    'labels.deleteResultConfirm': 'Bu sonucu silmek istediğinizden emin misiniz?',
    'labels.deleteResultWarning': 'Bu işlem geri alınamaz ve sonuç kalıcı olarak silinecektir.',
    'labels.deleteGroupConfirm': 'Bu grubu silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'labels.deleteGroupConfirmNamed': '"{name}" grubunu silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'labels.bulkDeleteGroupsConfirm': '{count} adet grubu silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'labels.deleteOrganizationConfirm': 'Bu organizasyonu silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'labels.bulkDeleteOrganizationsConfirm': '{count} adet organizasyonu silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'labels.bulkDeleteWarning': 'Bu işlem geri alınamaz ve seçili sonuçlar kalıcı olarak silinecektir.',
    'labels.customerFocusScore': 'Müşteri Odaklılık Skoru',
    'labels.adaptabilityScore': 'Uyumluluk ve Dayanıklılık Skoru',
    'labels.influenceScore': 'İnsanları Etkileme Skoru',
    'labels.trustScore': 'Güven Veren İşbirliği ve Sinerji Skoru',
    'labels.personScoresSheet': 'Kişi Skorları',
    'labels.pdfPreview': 'PDF Önizleme',
    'labels.pdfLoading': 'PDF yükleniyor...',
    'labels.notEnoughData': 'Yeterli veri yok',
    'labels.authorizationsLoading': 'Yetkilendirmeler yükleniyor...',
    'labels.organizationsLoading': 'Organizasyonlar yükleniyor...',
    'labels.groupsLoading': 'Gruplar yükleniyor...',
    'labels.groups': 'Gruplar',
    'labels.groupName': 'Grup Adı',
    'labels.status': 'Durum',
    'labels.details': 'Detaylar',
    'labels.competenciesLoading': 'Yetkinlikler yükleniyor...',
    'labels.selection': 'Seçim',
    'labels.selectPositionAvailable': 'Pozisyon seçin ({count} pozisyon mevcut)',
    'labels.row': 'Satır',
    'labels.errors': 'Hatalar',
    'labels.invalidRows': 'Hatalı satırlar',
    'labels.startDate': 'Başlangıç Tarihi',
    'labels.endDate': 'Bitiş Tarihi',
    'labels.minimum': 'Minimum',
    'labels.maximum': 'Maksimum',
    'labels.filterErrorTitle': 'Filtre Hatası',
    'labels.noData': 'Veri yok',
    'labels.totalCredits': 'Toplam Kredi',
    'labels.credits': 'Kredi',
    'labels.fee': 'Ücret',
    'labels.monthlyFeeSample': '120$ /Aylık',
    'labels.creditUsage': 'Kredi Kullanımları',
    'labels.usageSinceSample': '10/04/2025 12:16 tarihinden bugüne',
    'labels.remainingUsage': 'Kalan Kullanımlarım',
    'labels.usedUsage': 'Harcanan Kullanımlarım',
    'labels.date': 'Tarih',
    'labels.invoiceNo': 'Fatura No',
    'labels.invoice': 'Fatura',
    'labels.invoicePdf': 'Fatura PDF',
    'labels.credit': 'Kredi',
    'labels.loading': 'Yükleniyor...',
    'labels.authorizationCheck': 'Yetki kontrolü yapılıyor...',
    'labels.noGameData': 'Henüz oyun verisi bulunmuyor',
    'labels.customerFocusMin': 'Müşteri Odaklılık Min Değer',
    'labels.customerFocusMax': 'Müşteri Odaklılık Max Değer',
    'labels.uncertaintyMin': 'Uyumluluk ve Dayanıklılık Min Değer',
    'labels.uncertaintyMax': 'Uyumluluk ve Dayanıklılık Max Değer',
    'labels.ieMin': 'İnsanları Etkileme Min Değer',
    'labels.ieMax': 'İnsanları Etkileme Max Değer',
    'labels.idikMin': 'Güven Veren İşbirliği ve Sinerji Min Değer',
    'labels.idikMax': 'Güven Veren İşbirliği ve Sinerji Max Değer',
    'labels.competencySettingsSheet': 'Yetkinlik Ayarları',
    'labels.competencySettingsTemplateFile': 'yetkinlik_ayarlari_template.xlsx',
    'labels.deleteCompetencyConfirm': 'Bu yetkinlikleri silmek istediğinizden emin misiniz?',
    'labels.competencyDeleted': 'yetkinlik başarıyla silindi!',
    'labels.groupInfo': 'Grup Bilgileri',
    'labels.organizationSearchPlaceholderAvailable': 'Organizasyon arayın ({count} organizasyon mevcut)',
    'labels.personSearchPlaceholderAvailable': 'Kişi arayın ({count} kişi mevcut)',
    'labels.planetSearchPlaceholderAvailable': 'Gezegen arayın ({count} gezegen mevcut)',
    'labels.organizationNotFound': 'Organizasyon bulunamadı',
    'labels.noOrganizationYet': 'Henüz organizasyon bulunmuyor',
    'labels.personNotFound': 'Kişi bulunamadı',
    'labels.planetNotFound': 'Gezegen bulunamadı',
    'labels.bulkDelete': 'Toplu Sil',
    'labels.bulkDeleteWithCount': 'Toplu Sil ({count})',
    'labels.groupsEmpty': 'Henüz grup bulunmuyor',
    'labels.groupsNotFound': 'Arama kriterlerinize uygun grup bulunamadı',
    'labels.groupDetailsSubtitle': 'Grup bilgilerini güncelleyin ve organizasyonları, kişileri ve gezegenleri düzenleyin',
    'labels.planetVenus': 'Venüs',
    'labels.planetTitan': 'Titan',
    'labels.planets': 'Gezegenler',
    'labels.createdAt': 'Oluşturulma',
    'labels.unknown': 'Bilinmeyen',
    'labels.user': 'Kullanıcı',
    'labels.about': 'Hakkında',
    'labels.createGroupDesc': 'Yeni bir grup oluşturun ve organizasyonları, kişileri ve gezegenleri atayın',
    'labels.noOrganizationSelected': 'Henüz organizasyon seçilmedi',
    'labels.noPersonSelected': 'Henüz kişi seçilmedi',
    'labels.noPlanetSelected': 'Henüz gezegen seçilmedi',
    'labels.company': 'Firma',
    'labels.companyName': 'Firma Adı',
    'labels.companyEmail': 'Firma Maili',
    'labels.vkn': 'VKN',
    'labels.remainingGameCount': 'Kalan Oyun Sayısı',
    'labels.creditInfoTitle': 'Kredi Bilgisi:',
    'labels.creditInfoText': 'Kişi ve gezegen başına 1 kredi düşülür. Örnek: 2 kişiye 2 gezegen gönderilirse 4 kredi düşer.',
    'labels.autoRefundTitle': 'Otomatik İade:',
    'labels.autoRefundText': 'Hiç başlanmayıp süresi dolan oyunların kredisi otomatik olarak iade edilir.',
    'labels.person': 'Kişi',
    'labels.group': 'Grup',
    'labels.planetSelection': 'Gezegen Seçimi',
    'labels.groupSelection': 'Grup Seçimi',
    'labels.titleSelection': 'Unvan Seçimi',
    'labels.groupMembers': 'Grup Üyeleri',
    'labels.titleInfo': 'Unvan Bilgileri',
    'labels.titleMembers': 'Bu Unvanda Çalışan Kişiler',
    'labels.failedRecipients': 'Gönderilemeyen Kişiler:',
    'labels.organizationCount': 'Organizasyon Sayısı',
    'labels.competencyName': 'Yetkinlik Adı',
    'labels.fileUpload': 'CSV/Excel Dosyası',
    'labels.fileDropSelect': 'Excel dosyası seçin veya sürükleyin',
    'labels.fileFormats': '.csv, .xlsx veya .xls formatında dosya yükleyin',
    'labels.updating': 'Güncelleniyor...',
    'labels.deleting': 'Siliniyor...',
    'labels.planet': 'Gezegen',
    'labels.confirm': 'Onay',
    'labels.confirmSend': '{count} kişiye oyun kodu gönderilecek. Devam etmek istiyor musunuz?',
    'labels.warning': 'Uyarı',
    'labels.partialSuccess': 'Kısmi Başarı',
    'labels.unknownError': 'Bilinmeyen hata',
    'labels.personSend': 'Kişi gönderimi',
    'labels.groupSend': 'Grup gönderimi',
    'labels.groupSendPartial': 'Grup gönderimi (kısmi)',
    'labels.titleSend': 'Unvan gönderimi',
    'labels.titleSendPartial': 'Unvan gönderimi (kısmi)',
    'labels.gameDetailsLoading': 'Oyun detayları yükleniyor...',
    'labels.invoiceLoading': 'Fatura yükleniyor...',
    'labels.uploadInvoice': 'Fatura Yükle',
    'labels.uploadInvoiceOptional': 'Fatura Yükle (Opsiyonel)',
    'labels.deleteGameConfirm': 'Bu oyunu silmek istediğinizden emin misiniz?',
    'labels.deleteCompanyConfirm': '"{name}" firmasını silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'labels.companySelectAvailable': 'Firma seçin ({count} firma mevcut)',
    'labels.companyNotFound': 'Firma bulunamadı',
    'labels.loadingData': 'Veriler yükleniyor...',
    'labels.password': 'Şifre',
    'labels.resetCode': 'Doğrulama Kodu',
    'labels.newPassword': 'Yeni Şifre',
    'labels.confirmPassword': 'Şifre Tekrar',
    'labels.passwordRequirements': 'Şifre Kriterleri:',
    'labels.rememberMe': 'Beni Hatırla',
    'labels.forgotPassword': 'Şifremi Unuttum',
    'labels.backToLogin': '← Giriş sayfasına dön',
    'labels.allRightsReserved': '© 2025 Tüm Hakları Saklıdır',
    'labels.newPasswordOptional': 'Yeni Şifre (Opsiyonel)',
    'labels.deleteAdminConfirm': 'Bu admini silmek istediğinizden emin misiniz?',
    'labels.actionIrreversible': 'Bu işlem geri alınamaz!',
    'labels.deletePersonConfirm': 'Bu kişiyi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'labels.bulkDeleteAuthorizationsConfirm': '{count} adet yetkilendirmeyi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'labels.assessmentReport': 'DegerlendirmeRaporu',
    'labels.participation': 'Katılım',
    'labels.sampleParticipation': 'Ocak 2020',
    'labels.previousPeriodChange': 'Önceki döneme göre +0.7',
    'labels.positiveGrowth': '%75 pozitif gelişim',
    'labels.percentileRank': 'Percentile Sırası',
    'labels.companyOverall': 'Şirket genelinde',
    'labels.executiveSummarySample': 'Sarah Johnson, Q4 2024 değerlendirmesinde 8.4/10 genel skorla üstün performans göstermiştir.',
    'labels.executiveSummaryHighlights': 'En güçlü alanları Strategic Thinking, Problem Solving ve Leadership & Influence olarak öne çıkmaktadır.',
    'labels.fullReportSummary': 'Tüm yetkinlikler, 360° geri bildirimler ve gelişim önerileri.',
    'labels.sampleRole': 'Kıdemli Ürün Müdürü',
    'labels.registrationNumber': 'Sicil No',
    'labels.personName': 'Kişi Adı',
    'labels.email': 'Email',
    'labels.generalManagerAssistant': 'Genel Müdür Yardımcılığı',
    'labels.directorate': 'Direktörlük',
    'labels.management': 'Müdürlük',
    'labels.departmentLeadership': 'Departman/Şeflik',
    'labels.organizationTemplate': 'Organizasyon Template',
    'labels.organizationTemplateFile': 'organizasyon_template.xlsx',
    'labels.sampleGeneralManagerAssistant': 'Örnek Genel Müdür Yardımcılığı',
    'labels.sampleDirectorate': 'Örnek Direktörlük',
    'labels.sampleManagement': 'Örnek Müdürlük',
    'labels.sampleDepartmentLeadership': 'Örnek Departman/Şeflik',
    'labels.sampleTitle': 'Örnek Unvan',
    'labels.samplePosition': 'Örnek Pozisyon',
    'labels.addOrganizationDesc': 'Organizasyon bilgilerini girin',
    'labels.editOrganizationDesc': 'Organizasyon bilgilerini güncelleyin',
    'labels.positionNotFound': 'Pozisyon bulunamadı',
    'labels.noPeopleYet': 'Henüz kişi bulunmuyor',
    'labels.success': 'Başarılı!',
    'labels.error': 'Hata!',
    'labels.sendError': 'Gönderim hatası',
    'labels.excelImport': 'Excel Import',
    'labels.uploadExcelFile': 'Excel Dosyası Yükle',
    'labels.selectOrDropExcel': 'Excel dosyasını seçin veya sürükleyin',
    'labels.selectedFile': 'Seçilen dosya',
    'labels.uploading': 'Yükleniyor...',
    'labels.excelUploading': 'Excel dosyası yükleniyor...',
    'labels.supportedFormats': '.xlsx, .xls formatları desteklenir',
    'labels.peopleTemplate': 'Kişiler Template',
    'labels.peopleTemplateFile': 'kisiler_template.xlsx',
    'labels.actions': 'İşlemler',
    'placeholders.registrationNumber': 'Lütfen Sicil No Giriniz',
    'placeholders.personName': 'Lütfen Kişi Adını Giriniz',
    'placeholders.email': 'Lütfen Email Giriniz',
    'placeholders.positionSearch': 'Pozisyon ara...',
    'placeholders.groupSearch': 'Grup adında akıllı arama yapın...',
    'placeholders.groupName': 'Grup adını giriniz',
    'placeholders.competencySearch': 'Yetkinlik adında akıllı arama yapın...',
    'placeholders.companySearch': 'Firma ara...',
    'placeholders.companyName': 'Firma adını giriniz',
    'placeholders.companyEmail': 'Firma e-postasını giriniz',
    'placeholders.vkn': 'VKN giriniz',
    'placeholders.nameSurname': 'Lütfen Ad Soyad Giriniz',
    'placeholders.selectPlanet': 'Lütfen Gezegen Seçiniz',
    'placeholders.searchPlanet': 'Gezegen ara...',
    'placeholders.selectGroup': 'Lütfen Grup Seçiniz',
    'placeholders.searchGroup': 'Grup ara...',
    'placeholders.selectTitle': 'Lütfen Unvan Seçiniz',
    'placeholders.searchTitle': 'Unvan ara...',
    'placeholders.searchCompany': 'Firma ara...',
    'placeholders.searchByNameSmart': 'Kişi adına göre akıllı arama yapın...',
    'placeholders.selectCompetency': 'Yetkinlik seçin...',
    'placeholders.gameSearch': "Firma adı ve fatura no'da akıllı arama yapın...",
    'placeholders.invoiceNo': 'Fatura numarasını giriniz',
    'placeholders.credit': 'Kredi miktarını giriniz',
    'placeholders.password': 'Şifre giriniz',
    'placeholders.resetCode': '6 haneli doğrulama kodunu girin',
    'placeholders.newPassword': 'Yeni şifrenizi girin',
    'placeholders.confirmPassword': 'Şifrenizi tekrar girin',
    'placeholders.newPasswordOptional': 'Yeni şifre giriniz (değiştirmek istemiyorsanız boş bırakın)',
    'placeholders.generalManagerAssistant': 'Genel Müdür Yardımcılığı girin',
    'placeholders.directorate': 'Direktörlük girin',
    'placeholders.management': 'Müdürlük girin',
    'placeholders.departmentLeadership': 'Departman/Şeflik girin',
    'placeholders.title': 'Unvan girin',
    'placeholders.position': 'Pozisyon girin',
    'buttons.uploadExcel': 'Excel Yükle',
    'buttons.downloadTemplate': 'Template İndir',
    'buttons.upload': 'Yükle',
    'buttons.previous': 'Önceki',
    'buttons.next': 'Sonraki',
    'buttons.yes': 'Evet',
    'buttons.no': 'Hayır',
    'buttons.addGroup': 'Yeni Grup Ekle',
    'buttons.updateGroup': 'Güncelle',
    'buttons.deleteGroup': 'Sil',
    'buttons.viewGroupDetails': 'Detayı Gör',
    'buttons.close': 'Kapat',
    'buttons.save': 'Kaydet',
    'buttons.viewInvoice': 'Faturayı Görüntüle',
    'buttons.view': 'Görüntüle',
    'buttons.send': 'Gönder',
    'buttons.sendGroupMembers': 'Grup Üyelerine Gönder',
    'buttons.sendTitleMembers': 'Bu Unvandaki Kişilere Gönder',
    'buttons.moreCredits': 'Daha Fazla Kredi',
    'buttons.updateReports': 'Raporları Güncelle',
    'buttons.updateIds': 'ID\'leri Güncelle',
    'errors.authorizationListLoad': 'Yetkilendirme listesi yüklenemedi',
    'errors.authorizationListFetch': 'Yetkilendirme listesi alınamadı',
    'errors.authorizationLoad': 'Yetkilendirmeler yüklenirken bir hata oluştu',
    'errors.organizationListFetch': 'Organizasyon listesi alınamadı',
    'errors.organizationLoadFailed': 'Organizasyonlar yüklenirken bir hata oluştu',
    'errors.organizationStructureExists': 'Bu organizasyon yapısı zaten mevcut! Aynı bilgilerle tekrar ekleyemezsiniz.',
    'errors.organizationAddError': 'Organizasyon eklenirken bir hata oluştu',
    'errors.organizationUpdateError': 'Organizasyon güncellenirken bir hata oluştu',
    'errors.organizationDeleteError': 'Organizasyon silinirken bir hata oluştu',
    'errors.invalidExcelFormat': 'Dosya formatı hatalı. Lütfen geçerli bir Excel dosyası seçin.',
    'errors.serverUnreachable': 'Sunucuya bağlanılamıyor. İnternet bağlantınızı kontrol edin.',
    'errors.dataLoadFailed': 'Veriler yüklenemedi',
    'errors.competencyAddFailed': 'Yetkinlik eklenemedi',
    'errors.competencyAddError': 'Yetkinlik eklenirken bir hata oluştu',
    'errors.competencyIdMissing': 'Yetkinlik oluşturuldu ancak ID alınamadı',
    'errors.competencyUpdateFailed': 'Yetkinlik güncellenemedi',
    'errors.competencyUpdateError': 'Yetkinlik güncellenirken bir hata oluştu',
    'errors.competencyDeleteFailed': 'Bazı yetkinlikler silinemedi',
    'errors.competencyDeleteError': 'Yetkinlik silinirken bir hata oluştu',
    'errors.importFailed': 'Import işlemi başarısız!',
    'errors.importError': 'Import işlemi sırasında bir hata oluştu',
    'errors.serverError': 'Sunucu hatası',
    'errors.tryAgain': 'Lütfen tekrar deneyin',
    'errors.filterFailed': 'Filtreleme yapılırken bir hata oluştu!',
    'errors.startAfterEnd': 'Başlangıç tarihi bitiş tarihinden sonra olamaz!',
    'errors.minLessThanMax': 'Minimum değer maksimum değerden küçük olmalıdır!',
    'errors.noDataToDownload': 'İndirilecek veri bulunamadı.',
    'errors.excelDownloadFailed': 'Excel dosyası indirilirken bir hata oluştu!',
    'errors.invalidDate': 'Tarih formatı geçersiz',
    'errors.groupListLoad': 'Grup listesi yüklenemedi',
    'errors.groupListFetch': 'Grup listesi alınamadı',
    'errors.noDataForCode': 'Bu kod için veri bulunamadı.',
    'errors.answersFetchFailed': 'Cevaplar getirilemedi',
    'errors.wordDownloadFailed': 'Word indirme işlemi başarısız oldu',
    'errors.userInfoFetchFailed': 'Kullanıcı bilgileri alınamadı',
    'errors.groupsLoad': 'Gruplar yüklenirken bir hata oluştu',
    'errors.groupDataFetch': 'Grup verileri alınamadı',
    'errors.selectGroupToDelete': 'Lütfen silmek istediğiniz kayıtları seçiniz!',
    'errors.enterGroupName': 'Lütfen grup adını giriniz!',
    'errors.selectOrgOrPerson': 'Lütfen en az bir organizasyon veya kişi seçiniz!',
    'errors.selectPlanet': 'Lütfen en az bir gezegen seçiniz!',
    'errors.groupSaveFailed': 'Grup kaydedilemedi',
    'errors.groupSaveError': 'Grup kaydedilirken bir hata oluştu',
    'errors.groupDeleteFailed': 'Grup silinemedi',
    'errors.groupDeleteError': 'Grup silinirken bir hata oluştu',
    'errors.selectOrganization': 'Lütfen bir organizasyon seçin!',
    'errors.organizationAlreadySelected': 'Bu organizasyon zaten seçilmiş!',
    'errors.positionRequired': 'Pozisyon alanı boş olamaz!',
    'errors.titleRequired': 'Unvan alanı boş olamaz!',
    'errors.matchingPersonsFetch': 'Eşleşen kişiler alınamadı',
    'errors.pdfCreateFailed': 'PDF oluşturulurken bir hata oluştu',
    'errors.adminAddError': 'Admin eklenirken bir hata oluştu',
    'errors.adminUpdateError': 'Admin güncellenirken bir hata oluştu',
    'errors.adminDeleteError': 'Admin silinirken bir hata oluştu',
    'errors.companyAddError': 'Firma eklenirken bir hata oluştu',
    'errors.companyUpdateError': 'Firma güncellenirken bir hata oluştu',
    'errors.companyDeleteError': 'Firma silinirken bir hata oluştu',
    'errors.insufficientCredits': 'Yetersiz kredi! Mevcut kredi: {remaining}, Gerekli kredi: {needed}',
    'errors.creditDeductionFailed': 'Kredi düşürülemedi: {message}',
    'errors.sendFailed': 'Gönderilemedi: {message}',
    'errors.sendFailedGeneric': 'Gönderilemedi: Bir hata oluştu',
    'errors.codeGenerationFailed': 'Kod üretim hatası',
    'errors.codeGenerateMissing': 'Kod üretilemedi',
    'errors.gameDataFetch': 'Oyun verileri alınamadı',
    'errors.invoiceNotFound': 'Bu oyun için fatura dosyası bulunamadı!',
    'errors.invoicePreviewError': 'Fatura görüntülenirken bir hata oluştu',
    'errors.companyNameRequired': 'Firma adı zorunludur!',
    'errors.selectCompany': 'Lütfen firma seçiniz!',
    'errors.invoiceRequired': 'Fatura numarası zorunludur!',
    'errors.creditRequired': 'Geçerli bir kredi miktarı giriniz!',
    'errors.invoiceFileRequired': 'Fatura dosyası zorunludur!',
    'errors.gameAddError': 'Oyun eklenirken bir hata oluştu',
    'errors.gameUpdateFailed': 'Oyun güncellenemedi',
    'errors.gameUpdateError': 'Oyun güncellenirken bir hata oluştu',
    'errors.gameDeleteError': 'Oyun silinirken bir hata oluştu',
    'errors.fillAllFields': 'Lütfen tüm alanları doldurun',
    'errors.tooManyLoginAttempts': 'Çok fazla başarısız giriş denemesi. Lütfen birkaç dakika sonra tekrar deneyin.',
    'errors.invalidEmailPassword': 'E-posta veya şifre hatalı',
    'errors.loginFailed': 'Giriş yapılırken bir hata oluştu',
    'errors.emailRequired': 'Lütfen e-posta adresinizi girin',
    'errors.resetCodeSendFailed': 'Kod gönderilirken bir hata oluştu',
    'errors.resetCodeRequired': 'Lütfen doğrulama kodunu girin',
    'errors.resetCodeInvalid': 'Doğrulama kodu hatalı',
    'errors.resetCodeVerifyFailed': 'Kod doğrulanırken bir hata oluştu',
    'errors.passwordMismatch': 'Şifreler eşleşmiyor',
    'errors.passwordUpdateFailed': 'Şifre güncellenirken bir hata oluştu',
    'errors.titleListLoad': 'Unvan listesi yüklenemedi',
    'errors.titleListFetch': 'Unvan listesi alınamadı',
    'errors.selectGroup': 'Lütfen bir grup seçin!',
    'errors.groupAlreadySelected': 'Bu grup zaten seçilmiş!',
    'errors.selectTitle': 'Lütfen bir unvan seçin!',
    'errors.titleAlreadySelected': 'Bu unvan zaten seçilmiş!',
    'errors.planetAlreadySelected': 'Bu gezegen zaten seçilmiş!',
    'errors.groupDetailsLoad': 'Grup detayları yüklenemedi',
    'errors.titleDetailsLoad': 'Unvan detayları yüklenemedi',
    'errors.fillAllFieldsSelectPlanet': 'Lütfen tüm alanları doldurun ve en az bir gezegen seçin.',
    'errors.codeGenerateInvalid': 'Kod üretilemedi veya geçersiz kod döndü',
    'errors.selectTitleAtLeastOne': 'Lütfen en az bir unvan seçin!',
    'errors.selectPlanetAtLeastOne': 'Lütfen en az bir gezegen seçin!',
    'errors.noEmailInTitle': 'Seçilen unvanlarda email adresi olan kişi bulunamadı!',
    'errors.sendDuring': 'Gönderim sırasında bir hata oluştu!',
    'errors.selectGroupAtLeastOne': 'Lütfen en az bir grup seçin!',
    'errors.noEmailInGroup': 'Seçilen gruplarda email adresi olan kişi bulunamadı!',
    'errors.selectCsvOrExcel': 'Lütfen CSV (.csv) veya Excel (.xlsx, .xls) dosyası seçin!',
    'errors.selectCompetency': 'Lütfen bir yetkinlik seçin!',
    'errors.selectExcelFile': 'Lütfen bir Excel dosyası seçin!',
    'errors.fileUploadFailed': 'Dosya yüklenirken bir hata oluştu',
    'errors.selectCsvFile': 'Lütfen bir CSV dosyası seçin!',
    'errors.reportsUpdateFailed': 'Rapor güncelleme sırasında bir hata oluştu',
    'errors.idsUpdateFailed': 'ID güncelleme sırasında bir hata oluştu',
    'errors.selectRecordsToDelete': 'Lütfen silmek istediğiniz kayıtları seçiniz!',
    'errors.bulkDeleteFailed': 'Toplu silme işlemi sırasında bir hata oluştu',
    'errors.enterRegistrationNumber': 'Lütfen sicil numarasını giriniz!',
    'errors.enterPersonName': 'Lütfen kişi adını giriniz!',
    'errors.enterEmail': 'Lütfen email adresini giriniz!',
    'errors.selectPosition': 'Lütfen pozisyon seçiniz!',
    'errors.authorizationAddFailed': 'Yetkilendirme eklenemedi',
    'errors.authorizationAddError': 'Yetkilendirme eklenirken bir hata oluştu',
    'errors.authorizationUpdateFailed': 'Yetkilendirme güncellenemedi',
    'errors.authorizationUpdateError': 'Yetkilendirme güncellenirken bir hata oluştu',
    'errors.authorizationDeleteError': 'Yetkilendirme silinirken bir hata oluştu',
    'errors.templateDownloadError': 'Template indirilirken bir hata oluştu!',
    'errors.selectExcelFirst': 'Lütfen önce bir Excel dosyası seçin!',
    'errors.noPermissionRelogin': 'Yetkiniz bulunmuyor. Lütfen tekrar giriş yapın.',
    'errors.fileTooLarge': 'Dosya çok büyük. Lütfen daha küçük bir dosya seçin.',
    'errors.invalidFileFormat': 'Dosya formatı hatalı. Lütfen geçerli bir Excel dosyası seçin.',
    'errors.fileUploadError': 'Dosya yüklenirken bir hata oluştu.',
    'errors.onlyExcelAllowed': 'Lütfen sadece Excel dosyası (.xlsx, .xls) seçin!',
    'messages.authorizationAdded': 'Yetkilendirme başarıyla eklendi!',
    'messages.authorizationUpdated': 'Yetkilendirme başarıyla güncellendi!',
    'messages.authorizationDeleted': 'Yetkilendirme başarıyla silindi!',
    'messages.competencyAdded': 'Yetkinlik başarıyla eklendi!',
    'messages.competencyUpdated': 'Yetkinlik başarıyla güncellendi!',
    'messages.authorizationsDeleted': '{count} yetkilendirme başarıyla silindi.',
    'messages.templateDownloadSuccess': 'Excel template başarıyla indirildi!',
    'messages.groupCreated': 'Grup başarıyla oluşturuldu!',
    'messages.groupUpdated': 'Grup başarıyla güncellendi!',
    'messages.groupDeleted': 'Grup başarıyla silindi!',
    'messages.groupsDeleted': '{count} grup başarıyla silindi.',
    'messages.autoPersonsAdded': '{count} kişi otomatik olarak eklendi! ({positionCount} farklı pozisyondan)',
    'messages.organizationAdded': 'Organizasyon başarıyla eklendi!',
    'messages.organizationUpdated': 'Organizasyon başarıyla güncellendi!',
    'messages.organizationDeleted': 'Organizasyon başarıyla silindi!',
    'messages.organizationsDeleted': '{count} organizasyon başarıyla silindi.',
    'messages.noMatchingPositions': 'Seçilen organizasyonlarda eşleşen pozisyon bulunamadı.',
    'messages.gameAdded': 'Oyun başarıyla eklendi!',
    'messages.gameUpdated': 'Oyun başarıyla güncellendi!',
    'messages.gameDeleted': 'Oyun başarıyla silindi!',
    'messages.evaluationDeleted': 'Değerlendirme başarıyla silindi.',
    'warnings.selectRecordsToDelete': 'Lütfen silmek istediğiniz kayıtları seçiniz!',
    'titles.deleteResult': 'Sonucu Sil',
    'messages.resetCodeSent': 'Şifre sıfırlama kodu e-posta adresinize gönderildi',
    'messages.resetCodeVerified': 'Kod doğrulandı. Yeni şifrenizi belirleyin',
    'messages.passwordUpdated': 'Şifreniz başarıyla güncellendi. Giriş yapabilirsiniz',
    'login.welcome': 'Hoş Geldiniz',
    'login.forgotPassword': 'Şifremi Unuttum',
    'login.codeVerification': 'Kod Doğrulama',
    'login.resetPassword': 'Şifre Belirleme',
    'login.loginSubtitle': 'Devam etmek için lütfen giriş yapın',
    'login.emailSubtitle': 'E-posta adresinizi girin, size şifre sıfırlama kodu gönderelim',
    'login.codeSubtitle': 'E-posta adresinize gönderilen doğrulama kodunu girin',
    'login.resetSubtitle': 'Yeni şifrenizi belirleyin',
    'login.signingIn': 'Giriş yapılıyor...',
    'login.sendingCode': 'Kod gönderiliyor...',
    'login.verifyingCode': 'Kod doğrulanıyor...',
    'login.updatingPassword': 'Şifre güncelleniyor...',
    'login.signIn': 'Giriş Yap',
    'login.sendCode': 'Kod Gönder',
    'login.verifyCode': 'Kodu Doğrula',
    'login.updatePassword': 'Şifreyi Güncelle',
    'password.requirements.uppercase': 'Şifre en az 1 büyük harf içermelidir',
    'password.requirements.lowercase': 'Şifre en az 1 küçük harf içermelidir',
    'password.requirements.number': 'Şifre en az 1 sayı içermelidir',
    'password.requirements.special': 'Şifre en az 1 özel karakter (!@#$%^&* vb.) içermelidir',
    'password.requirements.minLength': 'Şifre en az {count} karakter olmalıdır',
    'password.valid': 'Şifre geçerli',
    'messages.fileUploadComplete': 'Dosya başarıyla yüklendi! Güncelleme butonlarına basarak işlemi tamamlayabilirsiniz.',
    'messages.reportsUpdated': 'Raporlar başarıyla güncellendi!',
    'messages.idsUpdated': 'ID\'ler başarıyla güncellendi!',
    'messages.peopleImportSuccess': 'Başarıyla {count} kişi eklendi!',
    'messages.codeSent': 'Kod başarıyla gönderildi! ({creditCost} kredi düşüldü)',
    'messages.sendSuccessNoCredit': '{count} kişiye başarıyla gönderildi!',
    'messages.sendSuccessWithCredit': '{count} kişiye başarıyla gönderildi! ({creditCost} kredi düşüldü)',
    'messages.sendPartialNoCredit': '{successCount} kişiye gönderildi, {errorCount} kişiye gönderilemedi.',
    'messages.sendPartialWithCredit': '{successCount} kişiye gönderildi, {errorCount} kişiye gönderilemedi. ({creditCost} kredi düşüldü)',
    'messages.sendNoRecipients': 'Hiçbir kişiye gönderilemedi!',
    'titles.addOrganization': 'Yeni Organizasyon Ekle',
    'titles.editOrganization': 'Organizasyon Düzenle',
    'titles.deleteOrganization': 'Organizasyonu Sil',
    'titles.bulkDeleteOrganizations': 'Toplu Silme',
    'titles.addCompetency': 'Yetkinlik Ekle',
    'titles.editCompetency': 'Yetkinlik Düzenle',
    'titles.deleteCompetency': 'Yetkinlik Sil',
    'titles.paymentHistory': 'Geçmiş Ödemeler',
    'titles.editGroup': 'Grup Düzenle',
    'titles.deleteGroup': 'Grup Sil',
    'titles.addAdmin': 'Admin Ekle',
    'titles.deleteAdmin': 'Admin Sil',
    'titles.editAdmin': 'Admin Düzenle',
    'titles.editGame': 'Oyun Düzenle',
    'titles.viewInvoice': 'Fatura Görüntüle',
    'titles.addCompany': 'Yeni Firma Ekle',
    'titles.deleteCompany': 'Firma Sil',
    'titles.editCompany': 'Firma Düzenle',
    'titles.adminPanel': 'Genel Takip Sistemi',
    'titles.andron': 'ANDRON',
    'titles.authorization': 'Kişiler',
    'titles.organization': 'Organizasyon',
    'titles.grouping': 'Gruplama',
    'titles.defineCompanyAdmin': 'Firma Admini Tanımlama',
    'titles.competencySettings': 'Yetkinlik Ayarları',
    'titles.subscriptionSettings': 'Abonelik Ayarları',
    'titles.gameSend': 'Oyun Gönderme',
    'titles.scriptFiles': 'Komut Dosyaları',
    'titles.gameManagement': 'Oyun Tanımlama',
    'titles.companyIdentification': 'Firma Tanımlama',
    'competency.customerFocus': 'Müşteri Odaklılık',
    'competency.uncertainty': 'Uyumluluk ve Dayanıklılık',
    'competency.ie': 'İnsanları Etkileme',
    'competency.idik': 'Güven Veren İşbirliği ve Sinerji',
    'competency.customerFocus.desc': 'Müşteri ihtiyaçlarını anlama ve çözüm üretme',
    'competency.uncertainty.desc': 'Belirsizliklerle başa çıkma ve dayanıklılık gösterme',
    'competency.ie.desc': 'İkna, etkileme ve yönlendirme becerileri',
    'competency.idik.desc': 'Ekip içinde güven, işbirliği ve uyum oluşturma',
    'status.completed': 'Tamamlandı',
    'status.inProgress': 'Oyun Devam Ediyor',
    'status.expired': 'Süresi Doldu',
    'status.pending': 'Beklemede',
    'status.sent': 'Gönderildi',
    'status.active': 'Aktif',
    'status.passive': 'Pasif',
    'labels.currentReport': 'Güncel Değerlendirme Özeti',
    'labels.fullReport': 'Tam Değerlendirme Raporu',
    'buttons.viewReport': 'Raporu Görüntüle',
    'buttons.downloadPdf': 'PDF İndir',
    'buttons.share': 'Paylaş',
    'labels.executiveSummarySubtitle': 'Q4 2024 değerlendirme sonuçlarının üst düzey özeti',
    'labels.generalSummary': 'Genel Özet',
    'labels.strengths': 'Güçlü Yönler',
    'labels.developmentAreas': 'Gelişim Alanları',
    'labels.competencyDetailsHeader': 'Yetkinlik Detayları',
    'labels.competencySelect': 'Yetkinlik Seç:',
    'labels.generalEvaluation': 'Genel Değerlendirme',
    'labels.definitionGeneralEvaluation': 'Tanım ve Genel Değerlendirme',
    'labels.strengthsDev': 'Güçlü Yönler & Gelişim Alanları',
    'labels.interviewQuestions': 'Mülakat Soruları',
    'labels.developmentPlan': 'Gelişim Planı',
    'labels.whyTheseQuestions': 'Neden Bu Sorular?',
    'labels.developmentArea': 'Gelişim Alanı',
    'labels.interviewQuestion': 'Mülakat Sorusu',
    'labels.followUpQuestion': 'Devam Sorusu',
    'labels.reportAccessTitle': 'Rapor Erişimi',
    'labels.reportAccessSubtitle': 'Tam raporu görüntüleyin, indirin veya paylaşın',
    'labels.adminUser': 'Admin',
    'labels.hrManager': 'İK Yöneticisi',
    'labels.reportInformationTitle': 'Rapor Bilgileri',
    'labels.reportTypeLabel': 'Rapor Türü',
    'labels.assessmentPeriodLabel': 'Değerlendirme Dönemi',
    'labels.reportPagesLabel': 'Rapor Sayfa Sayısı',
    'labels.fileSizeLabel': 'Dosya Boyutu',
    'labels.lastModifiedLabel': 'Son Güncelleme',
    'labels.reportTypeValue': 'Kapsamlı Değerlendirme',
    'labels.assessmentPeriodValue': 'Q4 2024',
    'labels.reportPagesValue': '24 sayfa',
    'labels.fileSizeValue': '2,4 MB',
    'labels.lastModifiedValue': '16 Aralık 2024',
    'labels.reportContentsTitle': 'Rapor İçeriği',
    'labels.reportContentsSubtitle': 'Rapor, 12 yetkinliğin detaylı analizini, benchmark karşılaştırmalarını ve gelişim önerilerini içerir.',
    'labels.reportContentItem1': 'Yönetici özeti ve temel bulgular',
    'labels.reportContentItem2': 'Detaylı yetkinlik kırılımları',
    'labels.reportContentItem3': 'Mülakat soruları ve konuşma başlıkları',
    'labels.reportContentItem4': 'Kişiselleştirilmiş gelişim planları',
    'labels.reportContentItem5': 'Tarihsel performans trendleri',
    'labels.recordsRange': '{start}-{end} arası, toplam {total} kayıt',
    'labels.resultsCount': '({count} sonuç)',
    'labels.noSearchResults': '"{query}" için arama sonucu bulunamadı',
    'labels.searchResultsCount': '"{term}" için {count} sonuç bulundu',
    'labels.excelFileName': 'Andron_Yetkinlik_Sonuçları_{date}_{time}.xlsx',
    'labels.dashboardExcelFileName': 'ANDRON_Kisi_Sonuclari_{date}.xlsx',
    'labels.showExpiredGames': 'Süresi Dolan Oyunları Göster',
    'labels.noAnswersFound': 'Bu oyun için cevap bulunamadı.',
    'labels.bulkDeleteConfirm': '{count} adet sonucu silmek istediğinizden emin misiniz?',
    'errors.pdfPreviewFailed': 'PDF önizlenirken bir hata oluştu',
    'errors.pdfDownloadFailed': 'PDF indirilirken bir hata oluştu',
    'messages.bulkDeleteSuccess': '{count} değerlendirme başarıyla silindi.',
    'messages.competenciesImportSuccess': 'Başarıyla {count} yetkinlik import edildi!',
    'buttons.ok': 'Tamam',
    'labels.outOf10': '10 üzerinden',
    'labels.yourScore': 'Skorunuz',
    'labels.overallPerformance': 'Genel Performans',
    'labels.trendLabel': 'Trend',
    'labels.performanceExcellent': 'MÜKEMMEL',
    'labels.performanceGrowing': 'GELİŞİYOR',
    'labels.performanceTopPercent': 'İLK %15',
    'labels.reportTitleQ4': 'Q4 2024 Raporu',
    'labels.aiAssistantSubtitle': 'Assessment sonuçlarına özel içgörüler ve öneriler yakında eklenecek.',
    'labels.viewOnline': 'Raporu Tarayıcıda Görüntüle',
    'labels.downloadReport': 'PDF İndir',
    'labels.shareReport': 'Raporu Paylaş',
    'labels.viewOnlineDesc': 'Raporu tarayıcıda görüntüle',
    'labels.downloadPdfDesc': 'Cihazınıza indirin',
    'labels.shareReportDesc': 'Paydaşlarla paylaşın',
    'labels.aiAssistantSoon': 'AI Asistan Yakında',
    'placeholders.searchAllColumns': 'Tüm sütunlarda akıllı arama yapın...',
    'placeholders.dateFormat': 'gg.aa.yyyy',
    'buttons.cancel': 'İptal',
    'buttons.add': 'Ekle',
    'buttons.update': 'Güncelle',
    'buttons.delete': 'Sil',
    'buttons.bulkDelete': 'Toplu Sil',
    'buttons.confirmDelete': 'Evet, Sil',
    'statuses.adding': 'Ekleniyor...',
    'statuses.updating': 'Güncelleniyor...',
    'statuses.deleting': 'Siliniyor...',
    'statuses.saving': 'Kaydediliyor...',
    'statuses.sending': 'Gönderiliyor...',
    'titles.addPerson': 'Kişi Ekle',
    'titles.deletePerson': 'Kişiyi Sil',
    'titles.editPerson': 'Kişi Düzenle',
    'titles.bulkDelete': 'Toplu Silme',
    'titles.filtering': 'Filtreleme',
    'titles.addGame': 'Oyun Ekle',
    'titles.deleteGame': 'Oyun Sil',
    'labels.title': 'Unvan',
    'labels.position': 'Pozisyon',
    'labels.noRecords': 'Kayıt bulunamadı',
    'buttons.clearFilters': 'Filtreleri Temizle',
    'buttons.applyFilters': 'Filtreleri Uygula',
    'buttons.switchToEnglish': 'İngilizceye geç',
    'buttons.switchToTurkish': 'Türkçeye geç'
  },
  en: {
    'nav.main': 'Main Menu',
    'nav.settings': 'Settings',
    'nav.companySettings': 'Company Settings',
    'nav.logout': 'Sign Out',
    'menu.dashboard': 'Dashboard',
    'menu.admin': 'General Tracking',
    'menu.personResults': 'Detailed Person Results',
    'menu.personScores': 'Person Scores',
    'menu.gameSend': 'Send Game',
    'menu.usageSummary': 'Game Usage Summary',
    'menu.companySetup': 'Company Setup',
    'menu.companyAdminSetup': 'Company Admin Setup',
    'menu.gameSetup': 'Game Setup',
    'menu.organization': 'Organization',
    'menu.competencySettings': 'Competency Settings',
    'menu.scriptFiles': 'Script Files',
    'titles.personResults': 'Person Evaluation Results',
    'titles.personReport': 'Comprehensive Assessment Report',
    'titles.personResultsSection': 'Person Results',
    'titles.personScores': 'Person Scores',
    'tabs.executiveSummary': 'Executive Summary',
    'tabs.competencyDetails': 'Competency Details',
    'tabs.reportAccess': 'Report Access',
    'tabs.aiAssistant': 'AI Assistant',
    'tabs.trend': 'Trend Analysis',
    'tabs.summary': 'Summary',
    'tabs.fullReport': 'Full Report',
    'labels.currentEvaluation': 'Latest Evaluation',
    'labels.completion': 'Completed',
    'labels.competencyStatus': 'Current Competency Status',
    'labels.competencyStatusDesc': 'Latest evaluation and benchmark results',
    'labels.reportDetails': 'Report Details',
    'labels.evaluationDate': 'Evaluation Date',
    'labels.trendAnalysis': 'Competency Trend Analysis',
    'labels.lastThreeResults': 'Results from the last 3 evaluations',
    'labels.selectCompetency': 'Select Competency',
    'labels.trendTip': 'Select a competency to view the trend on the right panel',
    'labels.currentTag': 'Current',
    'labels.comprehensiveAssessment': 'Q4 2024 Comprehensive Assessment',
    'labels.developingCompetency': 'Developing Competency',
    'titles.dashboard': 'Dashboard',
    'labels.gameSendStatus': 'Game Send Status',
    'labels.competencyDistributions': 'Competency Score Distributions',
    'labels.competencySelection': 'Competency Selection',
    'labels.competencyScore': 'Competency Score',
    'labels.peopleEvaluated': 'Number of People Evaluated',
    'labels.peopleCount': 'People Count',
    'labels.totalGamesSent': 'Total Games Sent',
    'labels.competencyGameDistribution': 'Game Distribution by Competency',
    'buttons.filter': 'Filter',
    'buttons.refresh': 'Refresh',
    'buttons.downloadResults': 'Download Results',
    'labels.loadingResults': 'Loading results...',
    'labels.noResults': 'No results found.',
    'labels.completionDate': 'Completion Date',
    'labels.detail': 'Detail',
    'labels.goToPersonResults': 'Go to detailed person result',
    'labels.nameSurname': 'Full Name',
    'labels.sentDate': 'Sent Date',
    'labels.codeExpiryDate': 'Code Expiry Date',
    'labels.reportExpiryDate': 'Report Expiry Date',
    'labels.evaluationReportFile': 'ANDRON_EvaluationReport',
    'labels.downloadPdf': 'Download PDF',
    'labels.downloadExcel': 'Download Excel',
    'labels.downloadWord': 'Download Word',
    'labels.viewAnswers': 'View Answers',
    'labels.hasUnplayedGame': 'There is an unplayed game',
    'labels.gameAnswersTitle': 'Game Answers',
    'labels.gameInfo': 'Game Info',
    'labels.code': 'Code',
    'labels.reportId': 'Report ID',
    'labels.question': 'Question',
    'labels.selectedAnswer1': 'Selected Answer 1',
    'labels.selectedAnswer2': 'Selected Answer 2',
    'labels.subCategory': 'Subcategory',
    'labels.preview': 'Preview',
    'labels.deleteResultConfirm': 'Are you sure you want to delete this result?',
    'labels.deleteResultWarning': 'This action cannot be undone and the result will be permanently deleted.',
    'labels.deleteGroupConfirm': 'Are you sure you want to delete this group? This action cannot be undone.',
    'labels.deleteGroupConfirmNamed': 'Are you sure you want to delete "{name}"? This action cannot be undone.',
    'labels.bulkDeleteGroupsConfirm': 'Are you sure you want to delete {count} groups? This action cannot be undone.',
    'labels.deleteOrganizationConfirm': 'Are you sure you want to delete this organization? This action cannot be undone.',
    'labels.bulkDeleteOrganizationsConfirm': 'Are you sure you want to delete {count} organizations? This action cannot be undone.',
    'labels.bulkDeleteWarning': 'This action cannot be undone and selected results will be permanently deleted.',
    'labels.customerFocusScore': 'Customer Focus Score',
    'labels.adaptabilityScore': 'Adaptability & Resilience Score',
    'labels.influenceScore': 'Influencing Others Score',
    'labels.trustScore': 'Trusting Collaboration & Synergy Score',
    'labels.personScoresSheet': 'Person Scores',
    'labels.pdfPreview': 'PDF Preview',
    'labels.pdfLoading': 'Loading PDF...',
    'labels.notEnoughData': 'Not enough data',
    'labels.authorizationsLoading': 'Loading authorizations...',
    'labels.organizationsLoading': 'Loading organizations...',
    'labels.groupsLoading': 'Loading groups...',
    'labels.groups': 'Groups',
    'labels.groupName': 'Group Name',
    'labels.status': 'Status',
    'labels.details': 'Details',
    'labels.competenciesLoading': 'Loading competencies...',
    'labels.selection': 'Selection',
    'labels.selectPositionAvailable': 'Select position ({count} available)',
    'labels.row': 'Row',
    'labels.errors': 'Errors',
    'labels.invalidRows': 'Invalid rows',
    'labels.startDate': 'Start Date',
    'labels.endDate': 'End Date',
    'labels.minimum': 'Minimum',
    'labels.maximum': 'Maximum',
    'labels.filterErrorTitle': 'Filter Error',
    'labels.noData': 'No data',
    'labels.totalCredits': 'Total Credits',
    'labels.credits': 'Credits',
    'labels.fee': 'Fee',
    'labels.monthlyFeeSample': '$120 /Monthly',
    'labels.creditUsage': 'Credit Usage',
    'labels.usageSinceSample': 'Since 10/04/2025 12:16',
    'labels.remainingUsage': 'Remaining Usage',
    'labels.usedUsage': 'Used Usage',
    'labels.date': 'Date',
    'labels.invoiceNo': 'Invoice No',
    'labels.credit': 'Credit',
    'labels.loading': 'Loading...',
    'labels.authorizationCheck': 'Checking permissions...',
    'labels.noGameData': 'No game data available yet',
    'labels.customerFocusMin': 'Customer Focus Min Value',
    'labels.customerFocusMax': 'Customer Focus Max Value',
    'labels.uncertaintyMin': 'Adaptability & Resilience Min Value',
    'labels.uncertaintyMax': 'Adaptability & Resilience Max Value',
    'labels.ieMin': 'Influencing Others Min Value',
    'labels.ieMax': 'Influencing Others Max Value',
    'labels.idikMin': 'Trusting Collaboration & Synergy Min Value',
    'labels.idikMax': 'Trusting Collaboration & Synergy Max Value',
    'labels.competencySettingsSheet': 'Competency Settings',
    'labels.competencySettingsTemplateFile': 'competency_settings_template.xlsx',
    'labels.deleteCompetencyConfirm': 'Are you sure you want to delete these competencies?',
    'labels.competencyDeleted': 'competencies deleted successfully!',
    'labels.groupInfo': 'Group Info',
    'labels.organizationSearchPlaceholderAvailable': 'Search organization ({count} available)',
    'labels.personSearchPlaceholderAvailable': 'Search person ({count} available)',
    'labels.planetSearchPlaceholderAvailable': 'Search planet ({count} available)',
    'labels.organizationNotFound': 'Organization not found',
    'labels.noOrganizationYet': 'No organization yet',
    'labels.personNotFound': 'Person not found',
    'labels.planetNotFound': 'Planet not found',
    'labels.bulkDelete': 'Bulk Delete',
    'labels.bulkDeleteWithCount': 'Bulk Delete ({count})',
    'labels.groupsEmpty': 'No groups yet',
    'labels.groupsNotFound': 'No groups match your search criteria',
    'labels.groupDetailsSubtitle': 'Update group info and manage organizations, people, and planets',
    'labels.planetVenus': 'Venus',
    'labels.planetTitan': 'Titan',
    'labels.planets': 'Planets',
    'labels.createdAt': 'Created At',
    'labels.unknown': 'Unknown',
    'labels.user': 'User',
    'labels.about': 'About',
    'labels.createGroupDesc': 'Create a new group and assign organizations, people, and planets',
    'labels.noOrganizationSelected': 'No organization selected yet',
    'labels.noPersonSelected': 'No person selected yet',
    'labels.noPlanetSelected': 'No planet selected yet',
    'labels.company': 'Company',
    'labels.companyName': 'Company Name',
    'labels.companyEmail': 'Company Email',
    'labels.vkn': 'Tax ID',
    'labels.remainingGameCount': 'Remaining Game Count',
    'labels.creditInfoTitle': 'Credit Info:',
    'labels.creditInfoText': '1 credit is deducted per person and per planet. Example: 2 people and 2 planets cost 4 credits.',
    'labels.autoRefundTitle': 'Auto Refund:',
    'labels.autoRefundText': 'Credits for games that were never started and expired are automatically refunded.',
    'labels.person': 'Person',
    'labels.group': 'Group',
    'labels.planetSelection': 'Planet Selection',
    'labels.groupSelection': 'Group Selection',
    'labels.titleSelection': 'Title Selection',
    'labels.groupMembers': 'Group Members',
    'labels.titleInfo': 'Title Details',
    'labels.titleMembers': 'People in this Title',
    'labels.failedRecipients': 'Failed Recipients:',
    'labels.organizationCount': 'Organization Count',
    'labels.competencyName': 'Competency Name',
    'labels.fileUpload': 'CSV/Excel File',
    'labels.fileDropSelect': 'Select or drop an Excel file',
    'labels.fileFormats': 'Upload a .csv, .xlsx, or .xls file',
    'labels.updating': 'Updating...',
    'labels.deleting': 'Deleting...',
    'labels.planet': 'Planet',
    'labels.confirm': 'Confirm',
    'labels.confirmSend': '{count} people will receive a game code. Do you want to continue?',
    'labels.warning': 'Warning',
    'labels.partialSuccess': 'Partial Success',
    'labels.unknownError': 'Unknown error',
    'labels.personSend': 'Person send',
    'labels.groupSend': 'Group send',
    'labels.groupSendPartial': 'Group send (partial)',
    'labels.titleSend': 'Title send',
    'labels.titleSendPartial': 'Title send (partial)',
    'labels.gameDetailsLoading': 'Loading game details...',
    'labels.invoiceLoading': 'Loading invoice...',
    'labels.uploadInvoice': 'Upload Invoice',
    'labels.uploadInvoiceOptional': 'Upload Invoice (Optional)',
    'labels.deleteGameConfirm': 'Are you sure you want to delete this game?',
    'labels.deleteCompanyConfirm': 'Are you sure you want to delete "{name}"? This action cannot be undone.',
    'labels.companySelectAvailable': 'Select company ({count} available)',
    'labels.companyNotFound': 'Company not found',
    'labels.loadingData': 'Loading data...',
    'labels.password': 'Password',
    'labels.resetCode': 'Verification Code',
    'labels.newPassword': 'New Password',
    'labels.confirmPassword': 'Confirm Password',
    'labels.passwordRequirements': 'Password Requirements:',
    'labels.rememberMe': 'Remember Me',
    'labels.forgotPassword': 'Forgot Password',
    'labels.backToLogin': '← Back to login',
    'labels.allRightsReserved': '© 2025 All Rights Reserved',
    'labels.newPasswordOptional': 'New Password (Optional)',
    'labels.deleteAdminConfirm': 'Are you sure you want to delete this admin?',
    'labels.actionIrreversible': 'This action cannot be undone!',
    'labels.deletePersonConfirm': 'Are you sure you want to delete this person? This action cannot be undone.',
    'labels.bulkDeleteAuthorizationsConfirm': 'Are you sure you want to delete {count} authorizations? This action cannot be undone.',
    'labels.assessmentReport': 'AssessmentReport',
    'labels.participation': 'Participation',
    'labels.sampleParticipation': 'Jan 2020',
    'labels.previousPeriodChange': 'Change vs previous period: +0.7',
    'labels.positiveGrowth': '75% positive improvement',
    'labels.percentileRank': 'Percentile Rank',
    'labels.companyOverall': 'Company-wide',
    'labels.executiveSummarySample': 'Sarah Johnson delivered a strong performance in the Q4 2024 evaluation with an overall score of 8.4/10.',
    'labels.executiveSummaryHighlights': 'Top strengths include Strategic Thinking, Problem Solving, and Leadership & Influence.',
    'labels.fullReportSummary': 'All competencies, 360° feedback, and development recommendations.',
    'labels.sampleRole': 'Senior Product Manager',
    'labels.registrationNumber': 'Registration No',
    'labels.personName': 'Person Name',
    'labels.email': 'Email',
    'labels.generalManagerAssistant': 'General Manager Assistant',
    'labels.directorate': 'Directorate',
    'labels.management': 'Management',
    'labels.departmentLeadership': 'Department/Team Lead',
    'labels.organizationTemplate': 'Organization Template',
    'labels.organizationTemplateFile': 'organization_template.xlsx',
    'labels.sampleGeneralManagerAssistant': 'Sample General Manager Assistant',
    'labels.sampleDirectorate': 'Sample Directorate',
    'labels.sampleManagement': 'Sample Management',
    'labels.sampleDepartmentLeadership': 'Sample Department/Team Lead',
    'labels.sampleTitle': 'Sample Title',
    'labels.samplePosition': 'Sample Position',
    'labels.addOrganizationDesc': 'Enter organization details',
    'labels.editOrganizationDesc': 'Update organization details',
    'labels.positionNotFound': 'Position not found',
    'labels.noPeopleYet': 'No people yet',
    'labels.success': 'Success!',
    'labels.error': 'Error!',
    'labels.sendError': 'Send error',
    'labels.excelImport': 'Excel Import',
    'labels.uploadExcelFile': 'Upload Excel File',
    'labels.selectOrDropExcel': 'Select or drag the Excel file here',
    'labels.selectedFile': 'Selected file',
    'labels.uploading': 'Uploading...',
    'labels.excelUploading': 'Uploading Excel file...',
    'labels.supportedFormats': '.xlsx, .xls formats supported',
    'labels.peopleTemplate': 'People Template',
    'labels.peopleTemplateFile': 'people_template.xlsx',
    'labels.actions': 'Actions',
    'placeholders.registrationNumber': 'Please enter registration number',
    'placeholders.personName': 'Please enter person name',
    'placeholders.email': 'Please enter email',
    'placeholders.positionSearch': 'Search position...',
    'placeholders.groupSearch': 'Search by group name...',
    'placeholders.groupName': 'Enter group name',
    'placeholders.competencySearch': 'Search by competency name...',
    'placeholders.companySearch': 'Search company...',
    'placeholders.companyName': 'Enter company name',
    'placeholders.companyEmail': 'Enter company email',
    'placeholders.vkn': 'Enter Tax ID',
    'placeholders.nameSurname': 'Please enter full name',
    'placeholders.selectPlanet': 'Please select a planet',
    'placeholders.searchPlanet': 'Search planet...',
    'placeholders.selectGroup': 'Please select a group',
    'placeholders.searchGroup': 'Search group...',
    'placeholders.selectTitle': 'Please select a title',
    'placeholders.searchTitle': 'Search title...',
    'placeholders.searchByNameSmart': 'Search by name...',
    'placeholders.selectCompetency': 'Select a competency...',
    'placeholders.gameSearch': 'Search by company name or invoice number...',
    'placeholders.invoiceNo': 'Enter invoice number',
    'placeholders.credit': 'Enter credit amount',
    'placeholders.password': 'Enter password',
    'placeholders.resetCode': 'Enter the 6-digit verification code',
    'placeholders.newPassword': 'Enter your new password',
    'placeholders.confirmPassword': 'Re-enter your password',
    'placeholders.newPasswordOptional': 'Enter a new password (leave blank to keep current)',
    'placeholders.generalManagerAssistant': 'Enter general manager assistant',
    'placeholders.directorate': 'Enter directorate',
    'placeholders.management': 'Enter management',
    'placeholders.departmentLeadership': 'Enter department/team lead',
    'placeholders.title': 'Enter title',
    'placeholders.position': 'Enter position',
    'buttons.uploadExcel': 'Upload Excel',
    'buttons.downloadTemplate': 'Download Template',
    'buttons.upload': 'Upload',
    'buttons.previous': 'Previous',
    'buttons.next': 'Next',
    'buttons.yes': 'Yes',
    'buttons.no': 'No',
    'buttons.addGroup': 'Add New Group',
    'buttons.updateGroup': 'Update',
    'buttons.deleteGroup': 'Delete',
    'buttons.viewGroupDetails': 'View Details',
    'buttons.close': 'Close',
    'buttons.save': 'Save',
    'buttons.viewInvoice': 'View Invoice',
    'buttons.view': 'View',
    'buttons.send': 'Send',
    'buttons.sendGroupMembers': 'Send to Group Members',
    'buttons.sendTitleMembers': 'Send to People in this Title',
    'buttons.moreCredits': 'More Credits',
    'buttons.updateReports': 'Update Reports',
    'buttons.updateIds': 'Update IDs',
    'errors.authorizationListLoad': 'Authorization list could not be loaded',
    'errors.authorizationListFetch': 'Authorization list could not be fetched',
    'errors.authorizationLoad': 'An error occurred while loading authorizations',
    'errors.organizationListFetch': 'Organization list could not be fetched',
    'errors.organizationLoadFailed': 'An error occurred while loading organizations',
    'errors.organizationStructureExists': 'This organization structure already exists. You cannot add the same details again.',
    'errors.organizationAddError': 'An error occurred while adding the organization',
    'errors.organizationUpdateError': 'An error occurred while updating the organization',
    'errors.organizationDeleteError': 'An error occurred while deleting the organization',
    'errors.invalidExcelFormat': 'Invalid file format. Please select a valid Excel file.',
    'errors.serverUnreachable': 'Unable to reach the server. Please check your internet connection.',
    'errors.dataLoadFailed': 'Data could not be loaded',
    'errors.competencyAddFailed': 'Competency could not be added',
    'errors.competencyAddError': 'An error occurred while adding competency',
    'errors.competencyIdMissing': 'Competency created but no ID returned',
    'errors.competencyUpdateFailed': 'Competency could not be updated',
    'errors.competencyUpdateError': 'An error occurred while updating competency',
    'errors.competencyDeleteFailed': 'Some competencies could not be deleted',
    'errors.competencyDeleteError': 'An error occurred while deleting competency',
    'errors.importFailed': 'Import failed!',
    'errors.importError': 'An error occurred during import',
    'errors.serverError': 'Server error',
    'errors.tryAgain': 'Please try again',
    'errors.filterFailed': 'An error occurred while filtering!',
    'errors.startAfterEnd': 'Start date cannot be after end date!',
    'errors.minLessThanMax': 'Minimum must be less than maximum!',
    'errors.noDataToDownload': 'No data available to download.',
    'errors.excelDownloadFailed': 'An error occurred while downloading the Excel file!',
    'errors.invalidDate': 'Invalid date format',
    'errors.groupListLoad': 'Group list could not be loaded',
    'errors.groupListFetch': 'Group list could not be fetched',
    'errors.noDataForCode': 'No data found for this code.',
    'errors.answersFetchFailed': 'Answers could not be fetched',
    'errors.wordDownloadFailed': 'Word download failed',
    'errors.userInfoFetchFailed': 'User information could not be fetched',
    'errors.groupsLoad': 'An error occurred while loading groups',
    'errors.groupDataFetch': 'Group data could not be fetched',
    'errors.selectGroupToDelete': 'Please select the records you want to delete!',
    'errors.enterGroupName': 'Please enter group name!',
    'errors.selectOrgOrPerson': 'Please select at least one organization or person!',
    'errors.selectPlanet': 'Please select at least one planet!',
    'errors.groupSaveFailed': 'Group could not be saved',
    'errors.groupSaveError': 'An error occurred while saving the group',
    'errors.groupDeleteFailed': 'Group could not be deleted',
    'errors.groupDeleteError': 'An error occurred while deleting the group',
    'errors.selectOrganization': 'Please select an organization!',
    'errors.organizationAlreadySelected': 'This organization is already selected!',
    'errors.positionRequired': 'Position cannot be empty!',
    'errors.titleRequired': 'Title cannot be empty!',
    'errors.matchingPersonsFetch': 'Matching people could not be fetched',
    'errors.pdfCreateFailed': 'An error occurred while creating the PDF',
    'errors.adminAddError': 'An error occurred while adding admin',
    'errors.adminUpdateError': 'An error occurred while updating admin',
    'errors.adminDeleteError': 'An error occurred while deleting admin',
    'errors.companyAddError': 'An error occurred while adding company',
    'errors.companyUpdateError': 'An error occurred while updating company',
    'errors.companyDeleteError': 'An error occurred while deleting company',
    'errors.insufficientCredits': 'Insufficient credits! Remaining: {remaining}, Required: {needed}',
    'errors.creditDeductionFailed': 'Credit deduction failed: {message}',
    'errors.sendFailed': 'Send failed: {message}',
    'errors.sendFailedGeneric': 'Send failed: An error occurred',
    'errors.codeGenerationFailed': 'Code generation failed',
    'errors.codeGenerateMissing': 'Code could not be generated',
    'errors.gameDataFetch': 'Game data could not be fetched',
    'errors.invoiceNotFound': 'No invoice file found for this game!',
    'errors.invoicePreviewError': 'An error occurred while viewing the invoice',
    'errors.companyNameRequired': 'Company name is required!',
    'errors.selectCompany': 'Please select a company!',
    'errors.invoiceRequired': 'Invoice number is required!',
    'errors.creditRequired': 'Please enter a valid credit amount!',
    'errors.invoiceFileRequired': 'Invoice file is required!',
    'errors.gameAddError': 'An error occurred while adding the game',
    'errors.gameUpdateFailed': 'Game could not be updated',
    'errors.gameUpdateError': 'An error occurred while updating the game',
    'errors.gameDeleteError': 'An error occurred while deleting the game',
    'errors.fillAllFields': 'Please fill in all fields',
    'errors.tooManyLoginAttempts': 'Too many failed login attempts. Please try again in a few minutes.',
    'errors.invalidEmailPassword': 'Invalid email or password',
    'errors.loginFailed': 'An error occurred while signing in',
    'errors.emailRequired': 'Please enter your email address',
    'errors.resetCodeSendFailed': 'An error occurred while sending the code',
    'errors.resetCodeRequired': 'Please enter the verification code',
    'errors.resetCodeInvalid': 'Verification code is invalid',
    'errors.resetCodeVerifyFailed': 'An error occurred while verifying the code',
    'errors.passwordMismatch': 'Passwords do not match',
    'errors.passwordUpdateFailed': 'An error occurred while updating the password',
    'errors.titleListLoad': 'Title list could not be loaded',
    'errors.titleListFetch': 'Title list could not be fetched',
    'errors.selectGroup': 'Please select a group!',
    'errors.groupAlreadySelected': 'This group is already selected!',
    'errors.selectTitle': 'Please select a title!',
    'errors.titleAlreadySelected': 'This title is already selected!',
    'errors.planetAlreadySelected': 'This planet is already selected!',
    'errors.groupDetailsLoad': 'Group details could not be loaded',
    'errors.titleDetailsLoad': 'Title details could not be loaded',
    'errors.fillAllFieldsSelectPlanet': 'Please fill in all fields and select at least one planet.',
    'errors.codeGenerateInvalid': 'Code could not be generated or is invalid',
    'errors.selectTitleAtLeastOne': 'Please select at least one title!',
    'errors.selectPlanetAtLeastOne': 'Please select at least one planet!',
    'errors.noEmailInTitle': 'No people with email found in selected titles!',
    'errors.sendDuring': 'An error occurred during sending!',
    'errors.selectGroupAtLeastOne': 'Please select at least one group!',
    'errors.noEmailInGroup': 'No people with email found in selected groups!',
    'errors.selectCsvOrExcel': 'Please select a CSV (.csv) or Excel (.xlsx, .xls) file!',
    'errors.selectCompetency': 'Please select a competency!',
    'errors.selectExcelFile': 'Please select an Excel file!',
    'errors.fileUploadFailed': 'An error occurred while uploading the file',
    'errors.selectCsvFile': 'Please select a CSV file!',
    'errors.reportsUpdateFailed': 'An error occurred while updating reports',
    'errors.idsUpdateFailed': 'An error occurred while updating IDs',
    'errors.selectRecordsToDelete': 'Please select the records you want to delete!',
    'errors.bulkDeleteFailed': 'An error occurred during bulk delete',
    'errors.enterRegistrationNumber': 'Please enter registration number!',
    'errors.enterPersonName': 'Please enter person name!',
    'errors.enterEmail': 'Please enter email address!',
    'errors.selectPosition': 'Please select a position!',
    'errors.authorizationAddFailed': 'Authorization could not be added',
    'errors.authorizationAddError': 'An error occurred while adding authorization',
    'errors.authorizationUpdateFailed': 'Authorization could not be updated',
    'errors.authorizationUpdateError': 'An error occurred while updating authorization',
    'errors.deleteFailed': 'Delete failed',
    'errors.authorizationDeleteError': 'An error occurred while deleting authorization',
    'errors.templateDownloadError': 'An error occurred while downloading the template!',
    'errors.selectExcelFirst': 'Please select an Excel file first!',
    'errors.noPermissionRelogin': 'You do not have permission. Please log in again.',
    'errors.fileTooLarge': 'File is too large. Please select a smaller file.',
    'errors.invalidFileFormat': 'Invalid file format. Please select a valid Excel file.',
    'errors.fileUploadError': 'An error occurred while uploading the file.',
    'errors.onlyExcelAllowed': 'Please select only Excel files (.xlsx, .xls)!',
    'messages.authorizationAdded': 'Authorization added successfully!',
    'messages.authorizationUpdated': 'Authorization updated successfully!',
    'messages.authorizationDeleted': 'Authorization deleted successfully!',
    'messages.competencyAdded': 'Competency added successfully!',
    'messages.competencyUpdated': 'Competency updated successfully!',
    'messages.authorizationsDeleted': '{count} authorizations deleted successfully.',
    'messages.templateDownloadSuccess': 'Excel template downloaded successfully!',
    'messages.gameAdded': 'Game added successfully!',
    'messages.gameUpdated': 'Game updated successfully!',
    'messages.gameDeleted': 'Game deleted successfully!',
    'messages.evaluationDeleted': 'Evaluation deleted successfully.',
    'warnings.selectRecordsToDelete': 'Please select the records you want to delete!',
    'titles.deleteResult': 'Delete Result',
    'messages.resetCodeSent': 'A password reset code has been sent to your email address',
    'messages.resetCodeVerified': 'Code verified. Please set your new password',
    'messages.passwordUpdated': 'Your password has been updated successfully. You can now sign in',
    'login.welcome': 'Welcome',
    'login.forgotPassword': 'Forgot Password',
    'login.codeVerification': 'Code Verification',
    'login.resetPassword': 'Set Password',
    'login.loginSubtitle': 'Please sign in to continue',
    'login.emailSubtitle': 'Enter your email and we will send a reset code',
    'login.codeSubtitle': 'Enter the verification code sent to your email',
    'login.resetSubtitle': 'Set your new password',
    'login.signingIn': 'Signing in...',
    'login.sendingCode': 'Sending code...',
    'login.verifyingCode': 'VerifyorganizationSearchPlaceholderAvailableing code...',
    'login.updatingPassword': 'Updating password...',
    'login.signIn': 'Sign In',
    'login.sendCode': 'Send Code',
    'login.verifyCode': 'Verify Code',
    'login.updatePassword': 'Update Password',
    'password.requirements.uppercase': 'Password must include at least 1 uppercase letter',
    'password.requirements.lowercase': 'Password must include at least 1 lowercase letter',
    'password.requirements.number': 'Password must include at least 1 number',
    'password.requirements.special': 'Password must include at least 1 special character (!@#$%^&* etc.)',
    'password.requirements.minLength': 'Password must be at least {count} characters',
    'password.valid': 'Password is valid',
    'messages.fileUploadComplete': 'File uploaded successfully! Complete the process by clicking the update buttons.',
    'messages.reportsUpdated': 'Reports updated successfully!',
    'messages.idsUpdated': 'IDs updated successfully!',
    'messages.peopleImportSuccess': '{count} people imported successfully!',
    'messages.codeSent': 'Code sent successfully! ({creditCost} credits deducted)',
    'messages.sendSuccessNoCredit': '{count} people sent successfully!',
    'messages.sendSuccessWithCredit': '{count} people sent successfully! ({creditCost} credits deducted)',
    'messages.sendPartialNoCredit': '{successCount} people sent, {errorCount} failed.',
    'messages.sendPartialWithCredit': '{successCount} people sent, {errorCount} failed. ({creditCost} credits deducted)',
    'messages.sendNoRecipients': 'No recipients could be sent!',
    'messages.groupCreated': 'Group created successfully!',
    'messages.groupUpdated': 'Group updated successfully!',
    'messages.groupDeleted': 'Group deleted successfully!',
    'messages.groupsDeleted': '{count} groups deleted successfully.',
    'messages.autoPersonsAdded': '{count} people were added automatically. ({positionCount} positions)',
    'messages.organizationAdded': 'Organization added successfully!',
    'messages.organizationUpdated': 'Organization updated successfully!',
    'messages.organizationDeleted': 'Organization deleted successfully!',
    'messages.organizationsDeleted': '{count} organizations deleted successfully.',
    'messages.noMatchingPositions': 'No matching positions found in the selected organizations.',
    'titles.addOrganization': 'Add New Organization',
    'titles.editOrganization': 'Edit Organization',
    'titles.deleteOrganization': 'Delete Organization',
    'titles.bulkDeleteOrganizations': 'Bulk Delete',
    'titles.addCompetency': 'Add Competency',
    'titles.editCompetency': 'Edit Competency',
    'titles.deleteCompetency': 'Delete Competency',
    'titles.paymentHistory': 'Payment History',
    'titles.editGroup': 'Edit Group',
    'titles.deleteGroup': 'Delete Group',
    'titles.addAdmin': 'Add Admin',
    'titles.deleteAdmin': 'Delete Admin',
    'titles.editAdmin': 'Edit Admin',
    'titles.addCompany': 'Add New Company',
    'titles.deleteCompany': 'Delete Company',
    'titles.editCompany': 'Edit Company',
    'titles.editGame': 'Edit Game',
    'titles.viewInvoice': 'View Invoice',
    'titles.adminPanel': 'General Tracking',
    'titles.authorization': 'People',
    'titles.organization': 'Organization',
    'titles.grouping': 'Grouping',
    'titles.defineCompanyAdmin': 'Define Company Admin',
    'titles.competencySettings': 'Competency Settings',
    'titles.subscriptionSettings': 'Subscription Settings',
    'titles.gameSend': 'Send Game',
    'titles.scriptFiles': 'Script Files',
    'titles.gameManagement': 'Game Management',
    'titles.companyIdentification': 'Company Identification',
    'competency.customerFocus': 'Customer Focus',
    'competency.uncertainty': 'Adaptability & Resilience',
    'competency.ie': 'Influencing Others',
    'competency.idik': 'Trusting Collaboration & Synergy',
    'competency.customerFocus.desc': 'Understanding customer needs and delivering solutions',
    'competency.uncertainty.desc': 'Handling uncertainty and demonstrating resilience',
    'competency.ie.desc': 'Persuasion, influence, and guidance skills',
    'competency.idik.desc': 'Building trust, collaboration, and alignment within teams',
    'status.completed': 'Completed',
    'status.inProgress': 'In Progress',
    'status.expired': 'Expired',
    'status.pending': 'Pending',  
    'status.sent': 'Sent',
    'status.active': 'Active',
    'status.passive': 'Passive',
    'labels.currentReport': 'Current Evaluation Summary',
    'labels.fullReport': 'Full Assessment Report',
    'buttons.viewReport': 'View Report',
    'buttons.downloadPdf': 'Download PDF',
    'buttons.share': 'Share',
    'labels.executiveSummarySubtitle': 'High-level summary of Q4 2024 evaluation results',
    'labels.generalSummary': 'General Summary',
    'labels.strengths': 'Strengths',
    'labels.developmentAreas': 'Development Areas',
    'labels.competencyDetailsHeader': 'Competency Details',
    'labels.competencySelect': 'Select Competency:',
    'labels.generalEvaluation': 'General Evaluation',
    'labels.definitionGeneralEvaluation': 'Definition and General Evaluation',
    'labels.strengthsDev': 'Strengths & Development Areas',
    'labels.interviewQuestions': 'Interview Questions',
    'labels.developmentPlan': 'Development Plan',
    'labels.whyTheseQuestions': 'Why These Questions?',
    'labels.developmentArea': 'Development Area',
    'labels.interviewQuestion': 'Interview Question',
    'labels.followUpQuestion': 'Follow-up Question',
    'labels.reportAccessTitle': 'Report Access',
    'labels.reportAccessSubtitle': 'View, download, or share the full report',
    'labels.adminUser': 'Admin User',
    'labels.hrManager': 'HR Manager',
    'labels.reportInformationTitle': 'Report Information',
    'labels.reportTypeLabel': 'Report Type',
    'labels.assessmentPeriodLabel': 'Assessment Period',
    'labels.reportPagesLabel': 'Report Pages',
    'labels.fileSizeLabel': 'File Size',
    'labels.lastModifiedLabel': 'Last Modified',
    'labels.reportTypeValue': 'Comprehensive Assessment',
    'labels.assessmentPeriodValue': 'Q4 2024',
    'labels.reportPagesValue': '24 pages',
    'labels.fileSizeValue': '2.4 MB',
    'labels.lastModifiedValue': 'December 16, 2024',
    'labels.reportContentsTitle': 'Report Contents',
    'labels.reportContentsSubtitle': 'The report includes detailed analyses of 12 competencies, benchmark comparisons, and development recommendations.',
    'labels.reportContentItem1': 'Executive summary and key findings',
    'labels.reportContentItem2': 'Detailed competency breakdowns',
    'labels.reportContentItem3': 'Interview questions and talking points',
    'labels.reportContentItem4': 'Personalized development plans',
    'labels.reportContentItem5': 'Historical performance trends',
    'labels.recordsRange': '{start}-{end} of {total} records',
    'labels.resultsCount': '({count} results)',
    'labels.noSearchResults': 'No search results for "{query}"',
    'labels.searchResultsCount': '{count} results found for "{term}"',
    'labels.excelFileName': 'Andron_Competency_Results_{date}_{time}.xlsx',
    'labels.dashboardExcelFileName': 'ANDRON_Person_Results_{date}.xlsx',
    'labels.showExpiredGames': 'Show Expired Games',
    'labels.noAnswersFound': 'No answers found for this game.',
    'labels.bulkDeleteConfirm': 'Are you sure you want to delete {count} results?',
    'errors.pdfPreviewFailed': 'An error occurred while previewing PDF',
    'errors.pdfDownloadFailed': 'An error occurred while downloading PDF',
    'messages.bulkDeleteSuccess': '{count} evaluations deleted successfully.',
    'messages.competenciesImportSuccess': '{count} competencies imported successfully!',
    'buttons.ok': 'OK',
    'labels.outOf10': 'out of 10',
    'labels.yourScore': 'Your Score',
    'labels.overallPerformance': 'Overall Performance',
    'labels.trendLabel': 'Trend',
    'labels.performanceExcellent': 'EXCELLENT',
    'labels.performanceGrowing': 'GROWING',
    'labels.performanceTopPercent': 'TOP 15%',
    'labels.reportTitleQ4': 'Q4 2024 Report',
    'labels.aiAssistantSubtitle': 'AI-driven insights and recommendations for assessment results are coming soon.',
    'labels.viewOnline': 'View Report Online',
    'labels.downloadReport': 'Download PDF',
    'labels.shareReport': 'Share Report',
    'labels.viewOnlineDesc': 'View the report in your browser',
    'labels.downloadPdfDesc': 'Download to your device',
    'labels.shareReportDesc': 'Share with stakeholders',
    'labels.aiAssistantSoon': 'AI Assistant Coming Soon',
    'placeholders.searchAllColumns': 'Search across all columns...',
    'placeholders.dateFormat': 'mm/dd/yyyy',
    'buttons.cancel': 'Cancel',
    'buttons.add': 'Add',
    'buttons.update': 'Update',
    'buttons.delete': 'Delete',
    'buttons.bulkDelete': 'Bulk Delete',
    'buttons.confirmDelete': 'Yes, Delete',
    'statuses.adding': 'Adding...',
    'statuses.updating': 'Updating...',
    'statuses.deleting': 'Deleting...',
    'statuses.saving': 'Saving...',
    'statuses.sending': 'Sending...',
    'titles.addPerson': 'Add Person',
    'titles.deletePerson': 'Delete Person',
    'titles.editPerson': 'Edit Person',
    'titles.bulkDelete': 'Bulk Delete',
    'titles.filtering': 'Filtering',
    'labels.title': 'Title',
    'labels.position': 'Position',
    'labels.noRecords': 'No records found',
    'buttons.clearFilters': 'Clear Filters',
    'buttons.applyFilters': 'Apply Filters',
    'buttons.switchToEnglish': 'Switch to English',
    'buttons.switchToTurkish': 'Switch to Turkish'
  }
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('appLanguage');
    return stored === 'en' ? 'en' : 'tr';
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => {
    const t = (key: string) => translations[language][key] || translations.tr[key] || key;
    return {
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((prev) => (prev === 'tr' ? 'en' : 'tr')),
      t
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
